package Salaries;

import Medical.coach_medical;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author faisa
 */
public class coach_salary extends javax.swing.JFrame {

    /**
     * Creates new form coach_salary
     */
    public coach_salary() {
        initComponents();
        
        Toolkit tk = getToolkit();
        Dimension size = tk.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insert_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        join_date = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        leave_date = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        c_bonus_tf = new javax.swing.JTextField();
        insert_btn1 = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        c_salary_tf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        c_id_tf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        insert_btn.setText("Insert");
        insert_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_btnActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(330, 350));
        setMinimumSize(new java.awt.Dimension(330, 350));
        setPreferredSize(new java.awt.Dimension(330, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Joinning Date:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));
        getContentPane().add(join_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 161, 150, 25));

        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Leaving Date:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        leave_date.setMinimumSize(new java.awt.Dimension(100, 25));
        leave_date.setPreferredSize(new java.awt.Dimension(100, 25));
        getContentPane().add(leave_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 211, 150, -1));

        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Coach Bonus:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        c_bonus_tf.setMinimumSize(new java.awt.Dimension(100, 25));
        c_bonus_tf.setPreferredSize(new java.awt.Dimension(100, 25));
        c_bonus_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_bonus_tfActionPerformed(evt);
            }
        });
        getContentPane().add(c_bonus_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 263, -1, -1));

        insert_btn1.setText("Insert");
        insert_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(insert_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 306, -1, -1));

        clear_btn.setText("Clear");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });
        getContentPane().add(clear_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 306, -1, -1));

        c_salary_tf.setMinimumSize(new java.awt.Dimension(100, 25));
        c_salary_tf.setPreferredSize(new java.awt.Dimension(100, 25));
        c_salary_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_salary_tfActionPerformed(evt);
            }
        });
        getContentPane().add(c_salary_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 111, -1, -1));

        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Coach Salary:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Coach Id:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        c_id_tf.setMinimumSize(new java.awt.Dimension(100, 25));
        c_id_tf.setPreferredSize(new java.awt.Dimension(100, 25));
        c_id_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_id_tfActionPerformed(evt);
            }
        });
        getContentPane().add(c_id_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 61, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Coach salary");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Medical/eleven.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insert_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_btnActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_insert_btnActionPerformed

    private void c_bonus_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_bonus_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_bonus_tfActionPerformed

    private void insert_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_btn1ActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            String query = "insert into [Coach Salary](C_ID,C_salary, joining_date, leaving_date, C_bonus)values(?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, c_id_tf.getText());
            pst.setString(2, c_salary_tf.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String j_date = sdf.format(join_date.getDate());
            pst.setString(3, j_date);
            String l_date = sdf.format(leave_date.getDate());
            pst.setString(4, l_date);
            pst.setString(5,c_bonus_tf.getText());

            pst.executeUpdate();
            /* DefaultTableModel model = (DefaultTableModel) player_jTable.getModel();
            model.setRowCount(0);
            show_player();*/

            coach_medical cm = new coach_medical();
            cm.setVisible(true);
            setVisible(false);

            //JOptionPane.showMessageDialog(null, "Inserted Sucessfully!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_insert_btn1ActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:
        c_salary_tf.setText("");
        c_salary_tf.setText("");
        c_bonus_tf.setText("");
    }//GEN-LAST:event_clear_btnActionPerformed

    private void c_salary_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_salary_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_salary_tfActionPerformed

    private void c_id_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_id_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_id_tfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(coach_salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(coach_salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(coach_salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(coach_salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new coach_salary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c_bonus_tf;
    private javax.swing.JTextField c_id_tf;
    private javax.swing.JTextField c_salary_tf;
    private javax.swing.JButton clear_btn;
    private javax.swing.JButton insert_btn;
    private javax.swing.JButton insert_btn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private com.toedter.calendar.JDateChooser join_date;
    private com.toedter.calendar.JDateChooser leave_date;
    // End of variables declaration//GEN-END:variables
}
