package Salaries;

import Medical.player_medical;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author faisa
 */
public class player_salary extends javax.swing.JFrame {

    /**
     * Creates new form player_salary
     */
    public player_salary() {
        initComponents();
        
        Toolkit tk = getToolkit();
        Dimension size = tk.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
        //data_show();
    }
    /*public void data_show() {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            String query = "SELECT TOP 1 P_ID FROM Player order by P_ID desc";
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
  
            
            while (rs.next()) {
                
                p_id_tf.setText(rs.getString(1));
            }
            
            
            
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }*/
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        p_salary_tf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        p_bonus_tf = new javax.swing.JTextField();
        insert_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        p_id_tf = new javax.swing.JTextField();
        join_date = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        leave_date = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(320, 380));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Player salary");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 14, -1, -1));

        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Player Id:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Player Salary:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Joinning Date:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        p_salary_tf.setMinimumSize(new java.awt.Dimension(100, 25));
        p_salary_tf.setPreferredSize(new java.awt.Dimension(100, 25));
        p_salary_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_salary_tfActionPerformed(evt);
            }
        });
        getContentPane().add(p_salary_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 133, -1, -1));

        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Player Bonus:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        p_bonus_tf.setMinimumSize(new java.awt.Dimension(100, 25));
        p_bonus_tf.setPreferredSize(new java.awt.Dimension(100, 25));
        p_bonus_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_bonus_tfActionPerformed(evt);
            }
        });
        getContentPane().add(p_bonus_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 284, 130, -1));

        insert_btn.setText("Insert");
        insert_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_btnActionPerformed(evt);
            }
        });
        getContentPane().add(insert_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 327, -1, -1));

        clear_btn.setText("Clear");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });
        getContentPane().add(clear_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 327, -1, -1));

        p_id_tf.setMinimumSize(new java.awt.Dimension(100, 25));
        p_id_tf.setPreferredSize(new java.awt.Dimension(100, 25));
        getContentPane().add(p_id_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 83, -1, -1));
        getContentPane().add(join_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 183, 150, 25));

        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Leaving Date:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));
        getContentPane().add(leave_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 233, 150, 25));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/image/eleven.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p_bonus_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_bonus_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_bonus_tfActionPerformed

    private void insert_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_btnActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            String query = "insert into [Player Salary](P_ID,P_salary, joining_date, leaving_date, P_bonus)values(?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, p_id_tf.getText());
            pst.setString(2, p_salary_tf.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String j_date = sdf.format(join_date.getDate());
            pst.setString(3, j_date);
            String l_date = sdf.format(leave_date.getDate());
            pst.setString(4, l_date);
            pst.setString(5,p_bonus_tf.getText());
            

            pst.executeUpdate();
           /* DefaultTableModel model = (DefaultTableModel) player_jTable.getModel();
            model.setRowCount(0);
            show_player();*/
            
            player_medical pm = new player_medical();
            pm.setVisible(true);
            setVisible(false);

            //JOptionPane.showMessageDialog(null, "Inserted Sucessfully!");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_insert_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:
        p_salary_tf.setText("");
        p_salary_tf.setText("");
        p_bonus_tf.setText("");
      
    }//GEN-LAST:event_clear_btnActionPerformed

    private void p_salary_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_salary_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_salary_tfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(player_salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(player_salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(player_salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(player_salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new player_salary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear_btn;
    private javax.swing.JButton insert_btn;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private com.toedter.calendar.JDateChooser join_date;
    private com.toedter.calendar.JDateChooser leave_date;
    private javax.swing.JTextField p_bonus_tf;
    private javax.swing.JTextField p_id_tf;
    private javax.swing.JTextField p_salary_tf;
    // End of variables declaration//GEN-END:variables
}
