package Home;

import Facilities.ground_gym;
import Revenue.Revenue;
import Sponsors.media;
import Staffs.coach;
import Staffs.p_player;
import Staffs.staff;
import Tournaments.la_liga;
import Tournaments.tournament;
import Tournaments.champions_league;
import Transfer.transfer;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author faisa
 */
public class window extends javax.swing.JFrame {

    /**
     * Creates new form window
     */
    public window() {
        initComponents();
        
        Toolkit tk = getToolkit();
        Dimension size = tk.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
        
        Next_match();
        Next_cl_oppo();
        Next_ll_oppo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Edit
     */
    
    public void Next_match(){
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
           
            String nx_date = "select Top 1 Match_Date,MIN (DATEDIFF(DD,GETDATE(),Match_Date)) as DDays from Tournament where GETDATE() <= match_date group by Match_Date order by DDays";
            PreparedStatement pst = con.prepareStatement(nx_date);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()) {
                n_m_date_l.setText(rs.getString(1));
            }
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }
    public void Next_cl_oppo(){
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
           
            String nx_date = "select Top 1 Tournament.Match_Date,[Champions league].Match_Opponent,MIN (DATEDIFF(DD,GETDATE(),Tournament.Match_Date)) as DDays from Tournament Inner join [Champions league] on Tournament.Match_Date = [Champions league].Match_Date where GETDATE() <= Tournament.Match_Date group by Tournament.Match_Date,[Champions league].Match_Opponent order by DDays";
            PreparedStatement pst = con.prepareStatement(nx_date);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()) {
                cl_date_l.setText(rs.getString(1));
                cl_oppo.setText(rs.getString(2));
            }
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }
    public void Next_ll_oppo(){
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
           
            String nx_date = "select Top 1 Tournament.Match_Date,[La Liga].Match_Opponent,MIN (DATEDIFF(DD,GETDATE(),Tournament.Match_Date)) as DDays from Tournament Inner join [La Liga] on Tournament.Match_Date = [La Liga].Match_Date where GETDATE() <= Tournament.Match_Date group by Tournament.Match_Date,[La Liga].Match_Opponent order by DDays";
            PreparedStatement pst = con.prepareStatement(nx_date);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()) {
                ll_date_l.setText(rs.getString(1));
                ll_oppo.setText(rs.getString(2));
            }
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tournament_menu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        n_m_date_l = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        coach_menu = new javax.swing.JLabel();
        palyer_menu = new javax.swing.JLabel();
        staff_menu = new javax.swing.JLabel();
        media_menu = new javax.swing.JLabel();
        gng_menu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tournament_cl = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cl_oppo = new javax.swing.JLabel();
        cl_date_l = new javax.swing.JLabel();
        transfer_window = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tournament_ll = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ll_date_l = new javax.swing.JLabel();
        ll_oppo = new javax.swing.JLabel();
        tournament_menu7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tournament_menu.setBackground(new java.awt.Color(255, 255, 255));
        tournament_menu.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.darkGray));
        tournament_menu.setForeground(new java.awt.Color(51, 51, 51));
        tournament_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tournament_menu.setPreferredSize(new java.awt.Dimension(164, 164));
        tournament_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tournament_menuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tournament_menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tournament_menuMouseExited(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/image/medal.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tournament");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 153));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Next Match:");

        n_m_date_l.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        n_m_date_l.setForeground(new java.awt.Color(0, 153, 153));
        n_m_date_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n_m_date_l.setText("        ");
        n_m_date_l.setPreferredSize(new java.awt.Dimension(30, 15));

        javax.swing.GroupLayout tournament_menuLayout = new javax.swing.GroupLayout(tournament_menu);
        tournament_menu.setLayout(tournament_menuLayout);
        tournament_menuLayout.setHorizontalGroup(
            tournament_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tournament_menuLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tournament_menuLayout.createSequentialGroup()
                .addGroup(tournament_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tournament_menuLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tournament_menuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addGap(10, 10, 10)
                        .addComponent(n_m_date_l, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );
        tournament_menuLayout.setVerticalGroup(
            tournament_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tournament_menuLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tournament_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(n_m_date_l, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(tournament_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 228, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 97, 142));
        jPanel2.setForeground(new java.awt.Color(51, 97, 142));
        jPanel2.setPreferredSize(new java.awt.Dimension(900, 180));

        jPanel1.setBackground(new java.awt.Color(51, 97, 142));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 53));

        coach_menu.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        coach_menu.setForeground(new java.awt.Color(255, 255, 255));
        coach_menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coach_menu.setText("Coach");
        coach_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coach_menuMouseClicked(evt);
            }
        });

        palyer_menu.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        palyer_menu.setForeground(new java.awt.Color(255, 255, 255));
        palyer_menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palyer_menu.setText("Player");
        palyer_menu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        palyer_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                palyer_menuMouseClicked(evt);
            }
        });

        staff_menu.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        staff_menu.setForeground(new java.awt.Color(255, 255, 255));
        staff_menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        staff_menu.setText("Staff");
        staff_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staff_menuMouseClicked(evt);
            }
        });

        media_menu.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        media_menu.setForeground(new java.awt.Color(255, 255, 255));
        media_menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        media_menu.setText("Media");
        media_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                media_menuMouseClicked(evt);
            }
        });

        gng_menu.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        gng_menu.setForeground(new java.awt.Color(255, 255, 255));
        gng_menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gng_menu.setText("Ground & Gym");
        gng_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gng_menuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(palyer_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(coach_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(staff_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(media_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(gng_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coach_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(palyer_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(staff_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(media_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gng_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        jLabel1.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Soccar Club Management System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 180));

        tournament_cl.setBackground(new java.awt.Color(255, 255, 255));
        tournament_cl.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.darkGray));
        tournament_cl.setForeground(new java.awt.Color(51, 51, 51));
        tournament_cl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tournament_cl.setPreferredSize(new java.awt.Dimension(164, 164));
        tournament_cl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tournament_clMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tournament_clMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tournament_clMouseExited(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/image/champ_l.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Champion's Leauge");

        cl_oppo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cl_oppo.setForeground(new java.awt.Color(0, 153, 153));
        cl_oppo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cl_oppo.setText("        ");
        cl_oppo.setPreferredSize(new java.awt.Dimension(30, 15));

        cl_date_l.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cl_date_l.setForeground(new java.awt.Color(0, 153, 153));
        cl_date_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cl_date_l.setText("        ");
        cl_date_l.setPreferredSize(new java.awt.Dimension(30, 15));

        javax.swing.GroupLayout tournament_clLayout = new javax.swing.GroupLayout(tournament_cl);
        tournament_cl.setLayout(tournament_clLayout);
        tournament_clLayout.setHorizontalGroup(
            tournament_clLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tournament_clLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
            .addGroup(tournament_clLayout.createSequentialGroup()
                .addGroup(tournament_clLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tournament_clLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tournament_clLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(cl_date_l, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cl_oppo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9))
        );
        tournament_clLayout.setVerticalGroup(
            tournament_clLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tournament_clLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tournament_clLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cl_oppo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cl_date_l, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(tournament_cl, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 228, -1, -1));

        transfer_window.setBackground(new java.awt.Color(255, 255, 255));
        transfer_window.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.darkGray));
        transfer_window.setForeground(new java.awt.Color(51, 51, 51));
        transfer_window.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        transfer_window.setPreferredSize(new java.awt.Dimension(164, 164));
        transfer_window.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transfer_windowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transfer_windowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transfer_windowMouseExited(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/image/transfer.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Transfer Window");

        javax.swing.GroupLayout transfer_windowLayout = new javax.swing.GroupLayout(transfer_window);
        transfer_window.setLayout(transfer_windowLayout);
        transfer_windowLayout.setHorizontalGroup(
            transfer_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transfer_windowLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transfer_windowLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
        transfer_windowLayout.setVerticalGroup(
            transfer_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transfer_windowLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel7)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(transfer_window, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, -1, -1));

        tournament_ll.setBackground(new java.awt.Color(255, 255, 255));
        tournament_ll.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.darkGray));
        tournament_ll.setForeground(new java.awt.Color(51, 51, 51));
        tournament_ll.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tournament_ll.setPreferredSize(new java.awt.Dimension(164, 164));
        tournament_ll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tournament_llMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tournament_llMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tournament_llMouseExited(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/image/football.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("La Liga");

        ll_date_l.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ll_date_l.setForeground(new java.awt.Color(0, 153, 153));
        ll_date_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ll_date_l.setText("        ");
        ll_date_l.setPreferredSize(new java.awt.Dimension(30, 15));

        ll_oppo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ll_oppo.setForeground(new java.awt.Color(0, 153, 153));
        ll_oppo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ll_oppo.setText("        ");
        ll_oppo.setPreferredSize(new java.awt.Dimension(30, 15));

        javax.swing.GroupLayout tournament_llLayout = new javax.swing.GroupLayout(tournament_ll);
        tournament_ll.setLayout(tournament_llLayout);
        tournament_llLayout.setHorizontalGroup(
            tournament_llLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tournament_llLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
            .addGroup(tournament_llLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tournament_llLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(ll_date_l, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ll_oppo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
        tournament_llLayout.setVerticalGroup(
            tournament_llLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tournament_llLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tournament_llLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ll_oppo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ll_date_l, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(tournament_ll, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 228, -1, -1));

        tournament_menu7.setBackground(new java.awt.Color(255, 255, 255));
        tournament_menu7.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.darkGray));
        tournament_menu7.setForeground(new java.awt.Color(51, 51, 51));
        tournament_menu7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tournament_menu7.setPreferredSize(new java.awt.Dimension(164, 164));
        tournament_menu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tournament_menu7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tournament_menu7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tournament_menu7MouseExited(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/image/wallet(1).png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Financial Condition");

        javax.swing.GroupLayout tournament_menu7Layout = new javax.swing.GroupLayout(tournament_menu7);
        tournament_menu7.setLayout(tournament_menu7Layout);
        tournament_menu7Layout.setHorizontalGroup(
            tournament_menu7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tournament_menu7Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tournament_menu7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        tournament_menu7Layout.setVerticalGroup(
            tournament_menu7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tournament_menu7Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(tournament_menu7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, -1));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/image/pp.jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 900, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void palyer_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_palyer_menuMouseClicked
        // TODO add your handling code here:
            p_player play = new p_player();
            play.setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_palyer_menuMouseClicked

    private void coach_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coach_menuMouseClicked
        // TODO add your handling code here:
            coach play = new coach();
            play.setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_coach_menuMouseClicked

    private void staff_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staff_menuMouseClicked
        // TODO add your handling code here:
            staff sf = new staff();
            sf.setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_staff_menuMouseClicked

    private void media_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_media_menuMouseClicked
        // TODO add your handling code here:
            media mid = new media();
            mid.setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_media_menuMouseClicked

    private void gng_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gng_menuMouseClicked
        // TODO add your handling code here:
            ground_gym gg = new ground_gym();
            gg.setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_gng_menuMouseClicked

    private void tournament_menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tournament_menuMouseEntered
        // TODO add your handling code here:
        setColor(tournament_menu);
    }//GEN-LAST:event_tournament_menuMouseEntered

    private void tournament_menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tournament_menuMouseExited
        // TODO add your handling code here:
        resetColor(tournament_menu);
    }//GEN-LAST:event_tournament_menuMouseExited

    private void tournament_clMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tournament_clMouseEntered
        // TODO add your handling code here:
        setColor(tournament_cl);
    }//GEN-LAST:event_tournament_clMouseEntered

    private void tournament_clMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tournament_clMouseExited
        // TODO add your handling code here:
        resetColor(tournament_cl);
    }//GEN-LAST:event_tournament_clMouseExited

    private void transfer_windowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transfer_windowMouseEntered
        // TODO add your handling code here:
        setColor(transfer_window);
    }//GEN-LAST:event_transfer_windowMouseEntered

    private void transfer_windowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transfer_windowMouseExited
        // TODO add your handling code here:
        resetColor(transfer_window);
    }//GEN-LAST:event_transfer_windowMouseExited

    private void tournament_llMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tournament_llMouseEntered
        // TODO add your handling code here:
        setColor(tournament_ll);
    }//GEN-LAST:event_tournament_llMouseEntered

    private void tournament_llMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tournament_llMouseExited
        // TODO add your handling code here:
        resetColor(tournament_ll);
    }//GEN-LAST:event_tournament_llMouseExited

    private void tournament_menu7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tournament_menu7MouseEntered
        // TODO add your handling code here:
        setColor(tournament_menu7);
    }//GEN-LAST:event_tournament_menu7MouseEntered

    private void tournament_menu7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tournament_menu7MouseExited
        // TODO add your handling code here:
        resetColor(tournament_menu7);
    }//GEN-LAST:event_tournament_menu7MouseExited

    private void tournament_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tournament_menuMouseClicked
        // TODO add your handling code here:
            tournament tour = new tournament();
            tour.setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_tournament_menuMouseClicked

    private void tournament_clMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tournament_clMouseClicked
        // TODO add your handling code here:
        champions_league cl = new champions_league();
            cl.setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_tournament_clMouseClicked

    private void tournament_llMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tournament_llMouseClicked
        // TODO add your handling code here:
        la_liga ll = new la_liga();
        ll.setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_tournament_llMouseClicked

    private void transfer_windowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transfer_windowMouseClicked
        // TODO add your handling code here:
        transfer tw = new transfer();
        tw.setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_transfer_windowMouseClicked

    private void tournament_menu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tournament_menu7MouseClicked
        // TODO add your handling code here:
        Revenue rv = new Revenue();
        rv.setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_tournament_menu7MouseClicked
    
    public void setColor(JPanel panel)
    {
        panel.setBackground(new java.awt.Color(170,170,170));
    }
    public void resetColor(JPanel panel)
    {
        panel.setBackground(new java.awt.Color(255,255,255));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cl_date_l;
    private javax.swing.JLabel cl_oppo;
    private javax.swing.JLabel coach_menu;
    private javax.swing.JLabel gng_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel ll_date_l;
    private javax.swing.JLabel ll_oppo;
    private javax.swing.JLabel media_menu;
    private javax.swing.JLabel n_m_date_l;
    private javax.swing.JLabel palyer_menu;
    private javax.swing.JLabel staff_menu;
    private javax.swing.JPanel tournament_cl;
    private javax.swing.JPanel tournament_ll;
    private javax.swing.JPanel tournament_menu;
    private javax.swing.JPanel tournament_menu7;
    private javax.swing.JPanel transfer_window;
    // End of variables declaration//GEN-END:variables
}
