package Staffs;

import Home.window;
import Medical.coach_medical;
import Salaries.coach_salary;
import Salaries.player_salary;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author faisa
 */
public class coach extends javax.swing.JFrame {

    /**
     * Creates new form coach
     */
    String m_area;

    String fileName = null;
    byte[] coach_img = null;

    public void visibility_true() {
        ci.setVisible(true);
        cs.setVisible(true);
        cy.setVisible(true);
        cv.setVisible(true);

        c_pay_id_tf.setVisible(true);
        c_salary_tf.setVisible(true);
        con_yr_tf.setVisible(true);
        c_bonus_tf.setVisible(true);

        CMI.setVisible(true);
        cy1.setVisible(true);
        pv1.setVisible(true);

        c_med_id_tf.setVisible(true);
        c_leave_tf.setVisible(true);
        med_des_tf.setVisible(true);

        up_salary.setVisible(true);
        up_ms.setVisible(true);
        ch_btn.setVisible(true);
        
        leave_date_l.setVisible(true);
        leave_date_d.setVisible(true);
        
        Injured_date_l.setVisible(true);
        injured_date_d.setVisible(true);
    }

    public void visibility_false() {

        ci.setVisible(false);
        cs.setVisible(false);
        cy.setVisible(false);
        cv.setVisible(false);

        c_pay_id_tf.setVisible(false);
        c_salary_tf.setVisible(false);
        con_yr_tf.setVisible(false);
        c_bonus_tf.setVisible(false);

        CMI.setVisible(false);
        cy1.setVisible(false);
        pv1.setVisible(false);

        c_med_id_tf.setVisible(false);
        c_leave_tf.setVisible(false);
        med_des_tf.setVisible(false);

        up_salary.setVisible(false);
        up_ms.setVisible(false);
        ch_btn.setVisible(false);

        leave_date_l.setVisible(false);
        leave_date_d.setVisible(false);
        
        Injured_date_l.setVisible(false);
        injured_date_d.setVisible(false);
    }

    public coach() {
        initComponents();
        show_coach();
        visibility_false();

        Toolkit tk = getToolkit();
        Dimension size = tk.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public ArrayList<coach_user> userList() {
        ArrayList<coach_user> userslist = new ArrayList();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            String query1 = "SELECT * FROM Coach";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);

            while (rs.next()) {
                coach_user user = new coach_user(rs.getInt("c_id"), rs.getString("c_name"), rs.getString("c_formation"), rs.getString("C_TYPE"), rs.getInt("c_age"), rs.getString("c_sex"), rs.getInt("c_rating"), rs.getString("c_m_issue"), rs.getBytes("c_Image"));
                userslist.add(user);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return userslist;
    }

    public void show_coach() {
        ArrayList<coach_user> list = userList();
        DefaultTableModel model = (DefaultTableModel) coach_jTable.getModel();
        Object[] row = new Object[8];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getcId();
            row[1] = list.get(i).getcName();
            row[2] = list.get(i).getcForm();
            row[3] = list.get(i).getcTYPE();
            row[4] = list.get(i).getcAge();
            row[5] = list.get(i).getcSex();
            row[6] = list.get(i).getcRating();
            row[7] = list.get(i).getcMIssue();
            model.addRow(row);
        }
    }

    public void Coach_salary() {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);

            int row = coach_jTable.getSelectedRow();
            String value = (coach_jTable.getModel().getValueAt(row, 0).toString());
            String query_cl = "select C_PAY_ID,C_salary,leaving_date,C_bonus from Coach right join [Coach Salary] on Coach.C_ID  = [Coach Salary].C_ID  where  Coach.C_ID  = " + value;
            String con_left ="select (DATEDIFF(MM,GETDATE(),leaving_date)) as Months from [Coach Salary]where (GETDATE() <= leaving_date and c_id ="+ value +" )group by leaving_date order by Months";
            PreparedStatement pst = con.prepareStatement(query_cl);
            ResultSet rs = pst.executeQuery();
            
            PreparedStatement pst_left = con.prepareStatement(con_left);
            ResultSet rs_left = pst_left.executeQuery();
           


            while (rs.next()) {

                c_pay_id_tf.setText(rs.getString(1));

                c_salary_tf.setText(rs.getString(2));

                leave_date_d.setDate(rs.getDate(3));

                c_bonus_tf.setText(rs.getString(4));
            }
            
            while (rs_left.next()) {
                con_yr_tf.setText(rs_left.getString(1));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void c_med_sts(){
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            
            
            int row = coach_jTable.getSelectedRow();
            String value = (coach_jTable.getModel().getValueAt(row, 0).toString());
            String query_sl = "select C_MED_ID ,LEAVE ,M_Description,injured_date from Coach right join [Coach Medical Status] on Coach.C_ID = [Coach Medical Status].C_ID where Coach.C_ID = " +value;
            String Leave_left = " select (DATEDIFF(DD,GETDATE(),(DATEADD(DD,leave,Injured_date)))) as DDays from [Coach Medical Status] where (GETDATE() >= Injured_date and C_ID = "+value+") group by Injured_date,LEAVE order by DDays";
            PreparedStatement pst = con.prepareStatement(query_sl);
            ResultSet rs = pst.executeQuery();
            
            PreparedStatement pst_left = con.prepareStatement(Leave_left);
            ResultSet rs_left = pst_left.executeQuery();
            
           /* pst.setString(1, p_pay_id_tf.getText());
            pst.setString(2, p_salary_tf.getText());
            pst.setString(3, con_yr_tf.getText());
            pst.setString(4, p_bonus_tf.getText());*/
            
            while (rs.next()) {
                
                c_med_id_tf.setText(rs.getString(1));

                c_leave_tf.setText(rs.getString(2));

                med_des_tf.setText(rs.getString(3));
                
                injured_date_d.setDate(rs.getDate(4));
                
            }
            while (rs_left.next()) {
                 c_leave_tf.setText(rs_left.getString(1));
            }
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void clr_data() {
        c_pay_id_tf.setText("");
        c_salary_tf.setText("");
        con_yr_tf.setText("");
        c_bonus_tf.setText("");

        c_med_id_tf.setText("");
        c_leave_tf.setText("");
        med_des_tf.setText("");

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img_l1 = new javax.swing.JLabel();
        pi = new javax.swing.JLabel();
        pi1 = new javax.swing.JLabel();
        p_pay_id_tf = new javax.swing.JLabel();
        asc = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmissue_tf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        male_radio = new javax.swing.JRadioButton();
        female_radio = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        formation_combo = new javax.swing.JComboBox<>();
        refresh_btn = new javax.swing.JButton();
        insert_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        coach_jTable = new javax.swing.JTable();
        back_btn1 = new javax.swing.JButton();
        c_age_tf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        c_rating_tf = new javax.swing.JTextField();
        c_name_tf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        img_l = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Type_combo = new javax.swing.JComboBox<>();
        ch_btn = new javax.swing.JButton();
        ci = new javax.swing.JLabel();
        cs = new javax.swing.JLabel();
        cy = new javax.swing.JLabel();
        cv = new javax.swing.JLabel();
        c_pay_id_tf = new javax.swing.JLabel();
        c_salary_tf = new javax.swing.JTextField();
        con_yr_tf = new javax.swing.JTextField();
        c_bonus_tf = new javax.swing.JTextField();
        up_salary = new javax.swing.JTextField();
        CMI = new javax.swing.JLabel();
        cy1 = new javax.swing.JLabel();
        pv1 = new javax.swing.JLabel();
        c_med_id_tf = new javax.swing.JLabel();
        c_leave_tf = new javax.swing.JTextField();
        med_des_tf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        srch_by_combo = new javax.swing.JComboBox<>();
        srch_C_name = new javax.swing.JTextField();
        up_ms = new javax.swing.JTextField();
        leave_date_d = new com.toedter.calendar.JDateChooser();
        Injured_date_l = new javax.swing.JLabel();
        injured_date_d = new com.toedter.calendar.JDateChooser();
        desc = new javax.swing.JLabel();
        asc1 = new javax.swing.JLabel();
        srch_p_range_1 = new javax.swing.JTextField();
        srch_p_range_2 = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        leave_date_l = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        img_l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        pi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pi.setText("Paying Id");

        pi1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pi1.setText("Paying Id");

        p_pay_id_tf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        asc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/image/up_d.png"))); // NOI18N
        asc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        asc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ascMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 505));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Age:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 185, -1, -1));

        cmissue_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmissue_tfActionPerformed(evt);
            }
        });
        getContentPane().add(cmissue_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 301, 161, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Medical Issue:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 304, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sex:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 220, -1, 20));

        male_radio.setForeground(new java.awt.Color(255, 255, 255));
        male_radio.setText("Male");
        male_radio.setBorder(null);
        male_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                male_radioActionPerformed(evt);
            }
        });
        getContentPane().add(male_radio, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 222, -1, 20));

        female_radio.setForeground(new java.awt.Color(255, 255, 255));
        female_radio.setText("Female");
        female_radio.setBorder(null);
        female_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                female_radioActionPerformed(evt);
            }
        });
        getContentPane().add(female_radio, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 222, -1, 20));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Formation:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 109, -1, -1));

        formation_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4-3-3", "4-2-3-1", "4-2-1-3", "4-2-2-2", "3-4-1-2", "4-1-4-1", "4-3-1-2" }));
        formation_combo.setBorder(null);
        formation_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formation_comboActionPerformed(evt);
            }
        });
        getContentPane().add(formation_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 110, 160, -1));

        refresh_btn.setText("Refresh");
        refresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_btnActionPerformed(evt);
            }
        });
        getContentPane().add(refresh_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 368, -1, -1));

        insert_btn.setText("Insert");
        insert_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_btnActionPerformed(evt);
            }
        });
        getContentPane().add(insert_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 355, -1, -1));

        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        getContentPane().add(update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 396, -1, -1));

        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        getContentPane().add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 396, -1, -1));

        clear_btn.setText("Clear");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });
        getContentPane().add(clear_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 355, -1, -1));

        coach_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Coach ID", "Coach Name", "Formation", "Type", "Age", "Sex", "Rating", "Medical Issue  "
            }
        ));
        coach_jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coach_jTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                coach_jTableMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(coach_jTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 690, 130));

        back_btn1.setText("Back");
        back_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(back_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        c_age_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_age_tfActionPerformed(evt);
            }
        });
        getContentPane().add(c_age_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 182, 60, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Rating:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 266, -1, -1));

        c_rating_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_rating_tfActionPerformed(evt);
            }
        });
        getContentPane().add(c_rating_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 263, 60, -1));

        c_name_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_name_tfActionPerformed(evt);
            }
        });
        getContentPane().add(c_name_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 68, 161, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Coach Name:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Coach");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 11, -1, -1));

        img_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(img_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, 130, 150));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(961, 459, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Type:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 147, -1, -1));

        Type_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Head", "Assistant", "Academy" }));
        Type_combo.setBorder(null);
        Type_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Type_comboActionPerformed(evt);
            }
        });
        getContentPane().add(Type_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 144, -1, -1));

        ch_btn.setText("Change");
        ch_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch_btnActionPerformed(evt);
            }
        });
        getContentPane().add(ch_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 430, -1, -1));

        ci.setForeground(new java.awt.Color(255, 255, 255));
        ci.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ci.setText("Paying Id");
        getContentPane().add(ci, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 250, -1, -1));

        cs.setForeground(new java.awt.Color(255, 255, 255));
        cs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cs.setText("Coach Salary");
        getContentPane().add(cs, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 250, 98, -1));

        cy.setForeground(new java.awt.Color(255, 255, 255));
        cy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cy.setText("Contract (Year)");
        getContentPane().add(cy, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 250, -1, -1));

        cv.setForeground(new java.awt.Color(255, 255, 255));
        cv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cv.setText("Performance Bonus");
        getContentPane().add(cv, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 250, -1, -1));

        c_pay_id_tf.setForeground(new java.awt.Color(255, 255, 255));
        c_pay_id_tf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(c_pay_id_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 270, 50, 20));

        c_salary_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(c_salary_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 270, 120, -1));

        con_yr_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        con_yr_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con_yr_tfActionPerformed(evt);
            }
        });
        getContentPane().add(con_yr_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 270, 108, -1));

        c_bonus_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(c_bonus_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 270, 108, -1));

        up_salary.setBackground(new java.awt.Color(240, 240, 240));
        up_salary.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        up_salary.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        up_salary.setText("Update");
        up_salary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                up_salaryMouseClicked(evt);
            }
        });
        up_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_salaryActionPerformed(evt);
            }
        });
        getContentPane().add(up_salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, -1, -1));

        CMI.setForeground(new java.awt.Color(255, 255, 255));
        CMI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CMI.setText("Medical Id");
        getContentPane().add(CMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 349, 55, -1));

        cy1.setForeground(new java.awt.Color(255, 255, 255));
        cy1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cy1.setText("Leave (Days)");
        getContentPane().add(cy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 349, -1, -1));

        pv1.setForeground(new java.awt.Color(255, 255, 255));
        pv1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pv1.setText("Description");
        getContentPane().add(pv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 351, 120, -1));

        c_med_id_tf.setForeground(new java.awt.Color(255, 255, 255));
        c_med_id_tf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(c_med_id_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 374, 55, 20));

        c_leave_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(c_leave_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 374, 64, -1));

        med_des_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(med_des_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 374, 186, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Search By");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, 32));

        srch_by_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "Formation", "Type", "Age", "Sex", "Rating", "Med issue" }));
        srch_by_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srch_by_comboActionPerformed(evt);
            }
        });
        getContentPane().add(srch_by_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 110, -1));

        srch_C_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srch_C_nameActionPerformed(evt);
            }
        });
        srch_C_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srch_C_nameKeyReleased(evt);
            }
        });
        getContentPane().add(srch_C_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 160, 25));

        up_ms.setBackground(new java.awt.Color(240, 240, 240));
        up_ms.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        up_ms.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        up_ms.setText("Update");
        up_ms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                up_msMouseClicked(evt);
            }
        });
        up_ms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_msActionPerformed(evt);
            }
        });
        getContentPane().add(up_ms, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, -1, -1));
        getContentPane().add(leave_date_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 130, -1));

        Injured_date_l.setForeground(new java.awt.Color(255, 255, 255));
        Injured_date_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Injured_date_l.setText("Injured Date");
        getContentPane().add(Injured_date_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, -1, 20));
        getContentPane().add(injured_date_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 130, -1));

        desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/image/down_d .png"))); // NOI18N
        desc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descMouseClicked(evt);
            }
        });
        getContentPane().add(desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 10, 20));

        asc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asc1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/image/up_d.png"))); // NOI18N
        asc1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        asc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                asc1MouseClicked(evt);
            }
        });
        getContentPane().add(asc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 10, 20));

        srch_p_range_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srch_p_range_1ActionPerformed(evt);
            }
        });
        srch_p_range_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srch_p_range_1KeyReleased(evt);
            }
        });
        getContentPane().add(srch_p_range_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 60, 25));

        srch_p_range_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srch_p_range_2ActionPerformed(evt);
            }
        });
        srch_p_range_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srch_p_range_2KeyReleased(evt);
            }
        });
        getContentPane().add(srch_p_range_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 60, 25));

        ok.setText("Ok");
        ok.setAlignmentY(0.0F);
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, -1, -1));

        leave_date_l.setForeground(new java.awt.Color(255, 255, 255));
        leave_date_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leave_date_l.setText("Releasing Date");
        getContentPane().add(leave_date_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, -1, 20));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Staffs/gg.png"))); // NOI18N
        jLabel8.setIconTextGap(0);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 505));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void male_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_male_radioActionPerformed
        // TODO add your handling code here:
        if (male_radio.isSelected()) {
            female_radio.setSelected(false);
        }
    }//GEN-LAST:event_male_radioActionPerformed

    private void female_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_female_radioActionPerformed
        // TODO add your handling code here:
        if (female_radio.isSelected()) {
            male_radio.setSelected(false);
        }
    }//GEN-LAST:event_female_radioActionPerformed

    private void refresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_btnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) coach_jTable.getModel();
        model.setRowCount(0);
        show_coach();
    }//GEN-LAST:event_refresh_btnActionPerformed

    private void insert_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_btnActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(null,"Choose a Photo for Player");
        image_choose();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            String query = "insert into Coach(c_name, c_formation,C_TYPE, c_age, c_sex, c_rating, c_m_issue,C_Image)values(?,?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, c_name_tf.getText());
            String m_result;
            String result;
            m_result = formation_combo.getSelectedItem().toString();
            pst.setString(2, m_result);

            result = Type_combo.getSelectedItem().toString();
            pst.setString(3, result);

            pst.setString(4, c_age_tf.getText());
            if (male_radio.isSelected()) {
                m_area = "Male";
            }
            if (female_radio.isSelected()) {
                m_area = "Female";
            }
            pst.setString(5, m_area);
            pst.setString(6, c_rating_tf.getText());
            pst.setString(7, cmissue_tf.getText());
            pst.setBytes(8, coach_img);

            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) coach_jTable.getModel();
            model.setRowCount(0);
            show_coach();
            
             clear();
            
            coach_salary  cs = new coach_salary ();
            cs.setVisible(true);
            
         


            JOptionPane.showMessageDialog(null, "Inserted Sucessfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_insert_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure to Delete?", "Delete", JOptionPane.YES_NO_CANCEL_OPTION);
        if (confirm == 0) {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
                Connection con = DriverManager.getConnection(url);
                int row = coach_jTable.getSelectedRow();
                String value = (coach_jTable.getModel().getValueAt(row, 0).toString());
                
                
                String sal = "Delete from [Coach Salary] where C_ID IN (Select C_ID  from Coach where C_ID ="+value+")";
                PreparedStatement sal_pst = con.prepareStatement(sal);
                sal_pst.executeUpdate();
                
                
                String med = "Delete from [Coach Salary] where C_ID IN (Select C_ID from Player where C_ID ="+value+")";
                PreparedStatement med_pst = con.prepareStatement(med);
                med_pst.executeUpdate();
                
                clr_data();
                
                
                
                String query = "Delete from Coach where C_ID =" + value;
                PreparedStatement pst = con.prepareStatement(query);
                pst.executeUpdate();
                DefaultTableModel model = (DefaultTableModel) coach_jTable.getModel();
                model.setRowCount(0);
                show_coach();

                JOptionPane.showMessageDialog(null, "Deleted Sucessfully!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_delete_btnActionPerformed

    public void clear() {

      c_name_tf.setText("");
        formation_combo.setSelectedIndex(-1);
        Type_combo.setSelectedIndex(-1);
        c_age_tf.setText("");
        male_radio.setSelected(false);
        female_radio.setSelected(false);
        c_rating_tf.setText("");
        cmissue_tf.setText("");

        clr_data();
        visibility_false();
        img_l.setIcon(null);
    }
    
    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:
      clear() ;
    }//GEN-LAST:event_clear_btnActionPerformed

    private void back_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btn1ActionPerformed
        // TODO add your handling code here:
        window field = new window();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_back_btn1ActionPerformed

    private void cmissue_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmissue_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmissue_tfActionPerformed

    private void c_age_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_age_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_age_tfActionPerformed

    private void c_rating_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_rating_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_rating_tfActionPerformed

    private void c_name_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_name_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_name_tfActionPerformed

    private void formation_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formation_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formation_comboActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            int row = coach_jTable.getSelectedRow();
            String value = (coach_jTable.getModel().getValueAt(row, 0).toString());
            String query = "Update Coach SET C_NAME = ? ,C_FORMATION = ? ,C_TYPE = ? ,C_AGE = ? ,C_SEX = ? ,C_RATING = ? ,C_M_issue = ? ,c_image = ? where C_ID =" + value;
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, c_name_tf.getText());
            String m_result;
            m_result = formation_combo.getSelectedItem().toString();
            pst.setString(2, m_result);
            String result;
            result = Type_combo.getSelectedItem().toString();
            pst.setString(3, result);
            pst.setString(4, c_age_tf.getText());
            if (male_radio.isSelected()) {
                m_area = "Male";
            }
            if (female_radio.isSelected()) {
                m_area = "Female";
            }
            pst.setString(5, m_area);
            pst.setString(6, c_rating_tf.getText());
            pst.setString(7, cmissue_tf.getText());
            pst.setBytes(8, coach_img);

            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) coach_jTable.getModel();
            model.setRowCount(0);
            show_coach();
            
             clear();

            JOptionPane.showMessageDialog(null, "Updated Sucessfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_update_btnActionPerformed

    private void coach_jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coach_jTableMouseClicked
        // TODO add your handling code here:
        int i = coach_jTable.getSelectedRow();
        TableModel model = coach_jTable.getModel();

        c_name_tf.setText(model.getValueAt(i, 1).toString());

        String form = model.getValueAt(i, 2).toString();
        switch (form) {
            case "4-3-3":
                formation_combo.setSelectedIndex(0);
                break;
            case "4-2-3-1":
                formation_combo.setSelectedIndex(1);
                break;
            case "4-2-1-3":
                formation_combo.setSelectedIndex(2);
                break;
            case "4-2-2-2":
                formation_combo.setSelectedIndex(3);
                break;
            case "3-4-1-2":
                formation_combo.setSelectedIndex(4);
                break;
            case "4-1-4-1":
                formation_combo.setSelectedIndex(5);
                break;
            case "4-3-1-2":
                formation_combo.setSelectedIndex(6);
                break;
        }

        String type = model.getValueAt(i, 3).toString();
        switch (type) {
            case "Head":
                Type_combo.setSelectedIndex(0);
                break;
            case "Assistant":
                Type_combo.setSelectedIndex(1);
                break;
            case "Academy":
                Type_combo.setSelectedIndex(2);
                break;
        }

        c_age_tf.setText(model.getValueAt(i, 4).toString());

        String area = model.getValueAt(i, 5).toString();
        if (area.equalsIgnoreCase("Male")) {
            male_radio.setSelected(true);
            female_radio.setSelected(false);
        }
        if (area.equalsIgnoreCase("Female")) {
            female_radio.setSelected(true);
            male_radio.setSelected(false);
        }

        c_rating_tf.setText(model.getValueAt(i, 6).toString());

        cmissue_tf.setText(model.getValueAt(i, 7).toString());

        visibility_true();
        Coach_salary();
        c_med_sts();

        try {
            byte[] img = (userList().get(i).getpImg());
            ImageIcon img_ic = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(img_l.getWidth(), img_l.getHeight(), Image.SCALE_SMOOTH));
            img_l.setIcon(img_ic);
        } catch (Exception e) {
            clr_data();
            System.out.println(e);
        }


    }//GEN-LAST:event_coach_jTableMouseClicked

    private void Type_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Type_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Type_comboActionPerformed

    public void image_choose() {
        JFileChooser choose = new JFileChooser();
        choose.showOpenDialog(null);
        File f = choose.getSelectedFile();
        fileName = f.getAbsolutePath();
        ImageIcon img_ic = new ImageIcon(new ImageIcon(fileName).getImage().getScaledInstance(img_l.getWidth(), img_l.getHeight(), Image.SCALE_SMOOTH));
        img_l.setIcon(img_ic);
        try {
            File image = new File(fileName);
            FileInputStream fi = new FileInputStream(image);
            ByteArrayOutputStream aos = new ByteArrayOutputStream();
            byte[] te = new byte[1024];
            for (int rn; (rn = fi.read(te)) != -1;) {
                aos.write(te, 0, rn);
            }
            coach_img = aos.toByteArray();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }


    private void ch_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch_btnActionPerformed
        // TODO add your handling code here:
        image_choose();
    }//GEN-LAST:event_ch_btnActionPerformed

    private void up_salaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_up_salaryMouseClicked
        // TODO add your handling code here:
        Date da = (Date) leave_date_d.getDate();
        SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
        String l_date = dt.format(da);
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            int row = coach_jTable.getSelectedRow();
            String value = c_pay_id_tf.getText().toString();
            String query = "Update [Coach Salary] SET C_salary = ? ,leaving_date = ? ,C_bonus = ? where C_PAY_ID =" + value;
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, c_salary_tf.getText());
            pst.setString(2, l_date);
            pst.setString(3, c_bonus_tf.getText());

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Updated Sucessfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_up_salaryMouseClicked
     public String srch_by_com;
     
     public void srch_combo_logic(){
        try {
            if (srch_by_combo.getSelectedItem().equals("Name")) {
                srch_by_com = "C_Name";
            } else if (srch_by_combo.getSelectedItem().equals("Formation")) {
                srch_by_com = "c_Formation";
            }else if(srch_by_combo.getSelectedItem().equals("Type")) {
                srch_by_com = "C_Type";
            } else if(srch_by_combo.getSelectedItem().equals("Age")) {
                srch_by_com = "c_Age";
            } else if(srch_by_combo.getSelectedItem().equals("Sex")) {
                srch_by_com = "c_Sex";
            } else if(srch_by_combo.getSelectedItem().equals("Rating")) {
                srch_by_com = "C_Rating";
            } else if(srch_by_combo.getSelectedItem().equals("Med Issue")) {
                srch_by_com = "c_M_Issue";
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    } 
    
    private void up_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_salaryActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_up_salaryActionPerformed

    private void srch_by_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srch_by_comboActionPerformed
        // TODO add your handling code here:
        srch_combo_logic();
    }//GEN-LAST:event_srch_by_comboActionPerformed

    private void srch_C_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srch_C_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srch_C_nameActionPerformed

    private void srch_C_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srch_C_nameKeyReleased
        // TODO add your handling code here:
        srch_combo_logic();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);

            TableModel model = coach_jTable.getModel();

            String value = srch_C_name.getText();
            String srch_by = srch_by_com.toString();
            String query = "Select C_ID,C_NAME,C_FORMATION,C_TYPE,C_AGE,C_SEX,C_RATING,C_M_issue from Coach"
            + " where " + srch_by + " LIKE '%"  + value + "%'";
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
           coach_jTable.setModel(DbUtils.resultSetToTableModel(rs));

           

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_srch_C_nameKeyReleased

    private void ascMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ascMouseClicked
        // TODO add your handling code here:
       

    }//GEN-LAST:event_ascMouseClicked

    private void asc1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asc1MouseClicked
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);

            TableModel model =coach_jTable.getModel();

            String value = srch_C_name.getText();
            String srch_by = srch_by_com.toString();
            String query = "Select C_ID,C_NAME,C_FORMATION,C_TYPE,C_AGE,C_SEX,C_RATING,C_M_issue from Coach "
            + " where " + srch_by + " LIKE '%"  + value + "%' order by " + srch_by + " asc ";
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            coach_jTable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_asc1MouseClicked

    private void descMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descMouseClicked
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);

            TableModel model = coach_jTable.getModel();

            String value = srch_C_name.getText();
            String srch_by = srch_by_com.toString();
            String query = "Select C_ID,C_NAME,C_FORMATION,C_TYPE,C_AGE,C_SEX,C_RATING,C_M_issue from Coach"
            + " where " + srch_by + " LIKE '%"  + value + "%' order by " + srch_by + " desc ";
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            coach_jTable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_descMouseClicked

    private void up_msMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_up_msMouseClicked
        // TODO add your handling code here:
        Date da = (Date) injured_date_d.getDate();
        SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
        String i_date = dt.format(da);
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            int row = coach_jTable.getSelectedRow();
            String value = c_med_id_tf.getText().toString();
            String query = "Update [coach Medical Status] SET LEAVE = ? ,M_Description = ?, Injured_date = ? where C_MED_ID = " + value;
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, c_leave_tf.getText());
            pst.setString(2, med_des_tf.getText());
            pst.setString(3, i_date);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Updated Sucessfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_up_msMouseClicked

    private void up_msActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_msActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_msActionPerformed

    private void coach_jTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coach_jTableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_coach_jTableMouseEntered

    private void con_yr_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con_yr_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_con_yr_tfActionPerformed

    private void srch_p_range_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srch_p_range_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srch_p_range_1ActionPerformed

    private void srch_p_range_1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srch_p_range_1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_srch_p_range_1KeyReleased

    private void srch_p_range_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srch_p_range_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srch_p_range_2ActionPerformed

    private void srch_p_range_2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srch_p_range_2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_srch_p_range_2KeyReleased

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);

            TableModel model = coach_jTable.getModel();

            String value1 = srch_p_range_1.getText().trim();
            String value2 = srch_p_range_2.getText().trim();
            String srch_by = srch_by_com.toString();
            String query = "Select c_ID,c_NAME,c_formation,c_type,c_AGE,c_SEX,c_RATING,c_M_issue from coach "
            + " where " + srch_by + " BETWEEN "  + value1 + " AND " + value2 + " order by " + srch_by;
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            coach_jTable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_okActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(coach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(coach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(coach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(coach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new coach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CMI;
    private javax.swing.JLabel Injured_date_l;
    private javax.swing.JComboBox<String> Type_combo;
    private javax.swing.JLabel asc;
    private javax.swing.JLabel asc1;
    private javax.swing.JButton back_btn1;
    private javax.swing.JTextField c_age_tf;
    private javax.swing.JTextField c_bonus_tf;
    private javax.swing.JTextField c_leave_tf;
    private javax.swing.JLabel c_med_id_tf;
    private javax.swing.JTextField c_name_tf;
    private javax.swing.JLabel c_pay_id_tf;
    private javax.swing.JTextField c_rating_tf;
    private javax.swing.JTextField c_salary_tf;
    private javax.swing.JButton ch_btn;
    private javax.swing.JLabel ci;
    private javax.swing.JButton clear_btn;
    private javax.swing.JTextField cmissue_tf;
    private javax.swing.JTable coach_jTable;
    private javax.swing.JTextField con_yr_tf;
    private javax.swing.JLabel cs;
    private javax.swing.JLabel cv;
    private javax.swing.JLabel cy;
    private javax.swing.JLabel cy1;
    private javax.swing.JButton delete_btn;
    private javax.swing.JLabel desc;
    private javax.swing.JRadioButton female_radio;
    private javax.swing.JComboBox<String> formation_combo;
    private javax.swing.JLabel img_l;
    private javax.swing.JLabel img_l1;
    private com.toedter.calendar.JDateChooser injured_date_d;
    private javax.swing.JButton insert_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser leave_date_d;
    private javax.swing.JLabel leave_date_l;
    private javax.swing.JRadioButton male_radio;
    private javax.swing.JTextField med_des_tf;
    private javax.swing.JButton ok;
    private javax.swing.JLabel p_pay_id_tf;
    private javax.swing.JLabel pi;
    private javax.swing.JLabel pi1;
    private javax.swing.JLabel pv1;
    private javax.swing.JButton refresh_btn;
    private javax.swing.JTextField srch_C_name;
    private javax.swing.JComboBox<String> srch_by_combo;
    private javax.swing.JTextField srch_p_range_1;
    private javax.swing.JTextField srch_p_range_2;
    private javax.swing.JTextField up_ms;
    private javax.swing.JTextField up_salary;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
