package Staffs;

import Home.window;
import Salaries.player_salary;
import Tournaments.tournament;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author faisa
 */
public class p_player extends javax.swing.JFrame {

    /**
     * Creates new form player
     */
    String m_area;
    String fileName = null;
    byte[] plr_img = null;

    public void visibility_true() {
        pi.setVisible(true);
        ps.setVisible(true);
        cy.setVisible(true);
        pv.setVisible(true);

        p_pay_id_tf.setVisible(true);
        p_salary_tf.setVisible(true);
        con_left_tf.setVisible(true);
        p_bonus_tf.setVisible(true);

        pi1.setVisible(true);
        cy1.setVisible(true);
        pv1.setVisible(true);
        leave_date_l.setVisible(true);
        leave_date_d.setVisible(true);

        p_med_id_tf.setVisible(true);
        p_leave_tf.setVisible(true);
        med_des_tf.setVisible(true);
        Injured_date_l.setVisible(true);
        injured_date_d.setVisible(true);

        up_salary.setVisible(true);
        up_ms.setVisible(true);
        ch_btn.setVisible(true);
        img_l.setVisible(true);
    }

    public void visibility_false() {
        pi.setVisible(false);
        ps.setVisible(false);
        cy.setVisible(false);
        pv.setVisible(false);

        p_pay_id_tf.setVisible(false);
        p_salary_tf.setVisible(false);
        con_left_tf.setVisible(false);
        p_bonus_tf.setVisible(false);

        pi1.setVisible(false);
        cy1.setVisible(false);
        pv1.setVisible(false);
        leave_date_l.setVisible(false);
        leave_date_d.setVisible(false);

        p_med_id_tf.setVisible(false);
        p_leave_tf.setVisible(false);
        med_des_tf.setVisible(false);
        Injured_date_l.setVisible(false);
        injured_date_d.setVisible(false);

        up_salary.setVisible(false);
        up_ms.setVisible(false);

        ch_btn.setVisible(false);
        img_l.setVisible(false);

        //srch_p_range_1.setVisible(false);
        //srch_p_range_2.setVisible(false);
        //ok.setVisible(false);
    }

    public p_player() {
        initComponents();
        pos_combo.setSelectedItem(null);
        show_player();
        visibility_false();

        Toolkit tk = getToolkit();
        Dimension size = tk.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

    }

    public p_player(String msg) {
        initComponents();
        p_name_tf.setText(msg);
        show_player();
        visibility_false();

        Toolkit tk = getToolkit();
        Dimension size = tk.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public ArrayList<player_User> userList() {
        ArrayList<player_User> userslist = new ArrayList();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            String query1 = "SELECT * FROM Player";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);

            while (rs.next()) {
                player_User user = new player_User(rs.getInt("p_id"), rs.getString("p_name"), rs.getString("P_POSSITION"), rs.getInt("p_age"), rs.getString("p_sex"), rs.getInt("p_weight"), rs.getInt("p_height"), rs.getString("p_nationality"), rs.getInt("p_rating"), rs.getString("p_m_issue"), rs.getBytes("P_Image"));
                userslist.add(user);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return userslist;
    }

    public void show_player() {
        ArrayList<player_User> list = userList();
        DefaultTableModel model = (DefaultTableModel) player_jTable.getModel();
        Object[] row = new Object[10];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getpId();
            row[1] = list.get(i).getpName();
            row[2] = list.get(i).getpPos();
            row[3] = list.get(i).getpAge();
            row[4] = list.get(i).getpSex();
            row[5] = list.get(i).getpWeight();
            row[6] = list.get(i).getpHeight();
            row[7] = list.get(i).getpNation();
            row[8] = list.get(i).getpRating();
            row[9] = list.get(i).getpMIssue();
            model.addRow(row);
        }
    }

    public void p_salary() {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);

            int row = player_jTable.getSelectedRow();
            String value = (player_jTable.getModel().getValueAt(row, 0).toString());
            String query_sl = "select P_PAY_ID,P_salary,leaving_date,P_bonus from Player right join [Player Salary] on Player.P_ID = [Player Salary].P_ID where Player.P_ID = " + value;
            String con_left = "select (DATEDIFF(MM,GETDATE(),leaving_date)) as Months from [Player Salary]where (GETDATE() <= leaving_date and p_id =" + value + " )group by leaving_date order by Months";
            PreparedStatement pst = con.prepareStatement(query_sl);
            ResultSet rs = pst.executeQuery();

            PreparedStatement pst_left = con.prepareStatement(con_left);
            ResultSet rs_left = pst_left.executeQuery();
            /* pst.setString(1, p_pay_id_tf.getText());
            pst.setString(2, p_salary_tf.getText());
            pst.setString(3, con_yr_tf.getText());
            pst.setString(4, p_bonus_tf.getText());*/

            while (rs.next()) {

                p_pay_id_tf.setText(rs.getString(1));

                p_salary_tf.setText(rs.getString(2));

                leave_date_d.setDate(rs.getDate(3));

                p_bonus_tf.setText(rs.getString(4));
            }

            while (rs_left.next()) {
                con_left_tf.setText(rs_left.getString(1));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /*
    int i = player_jTable.getSelectedRow();
            TableModel model = player_jTable.getModel();
            
            try {
                    Date dt = new SimpleDateFormat("yyyy-MM-dd").parse(((String) model.getValueAt(i, 5)));
                    leave_date_d.setDate(dt);
                } catch (ParseException ex) {
                    Logger.getLogger(tournament.class.getName()).log(Level.SEVERE, null, ex);
                }
     */
    public void p_med_sts() {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);

            int row = player_jTable.getSelectedRow();
            String value = (player_jTable.getModel().getValueAt(row, 0).toString());
            String query_sl = "select P_MED_ID,M_Description,injured_date from Player right join [Player Medical Status] on Player.P_ID = [Player Medical Status].P_ID where Player.P_ID = " + value;
            String Leave_left = " select (DATEDIFF(DD,GETDATE(),(DATEADD(DD,leave,Injured_date)))) as DDays from [Player Medical Status] where (GETDATE() >= Injured_date and P_ID = " + value + ") group by Injured_date,LEAVE order by DDays";
            PreparedStatement pst = con.prepareStatement(query_sl);
            ResultSet rs = pst.executeQuery();

            PreparedStatement pst_left = con.prepareStatement(Leave_left);
            ResultSet rs_left = pst_left.executeQuery();

            /* pst.setString(1, p_pay_id_tf.getText());
            pst.setString(2, p_salary_tf.getText());
            pst.setString(3, con_yr_tf.getText());
            pst.setString(4, p_bonus_tf.getText());*/
            while (rs.next()) {

                p_med_id_tf.setText(rs.getString(1));

                med_des_tf.setText(rs.getString(2));

                injured_date_d.setDate(rs.getDate(3));
            }

            while (rs_left.next()) {
                p_leave_tf.setText(rs_left.getString(1));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void p_transfer() {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);

            int row = player_jTable.getSelectedRow();
            String value = (player_jTable.getModel().getValueAt(row, 0).toString());
            String query_sl = "insert into [Transfer Sell] (P_ID,P_NAME) select P_ID,P_NAME from Player where P_ID = " + value;

            PreparedStatement pst = con.prepareStatement(query_sl);
            pst.executeUpdate();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public String best_11(String name) {
        String n = "";
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);

            int row = player_jTable.getSelectedRow();
            String value = (player_jTable.getModel().getValueAt(row, 0).toString());
            String query_sl = "select P_NAME from Player where P_ID = " + value;

            PreparedStatement pst = con.prepareStatement(query_sl);
            pst.executeUpdate();

            n = p_name_tf.getText();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return n;
    }

    public void clr_data() {
        p_pay_id_tf.setText("");
        p_salary_tf.setText("");
        con_left_tf.setText("");
        p_bonus_tf.setText("");

        p_med_id_tf.setText("");
        p_leave_tf.setText("");
        med_des_tf.setText("");

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        player_jTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        p_name_tf = new javax.swing.JTextField();
        pos_combo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        back_btn1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        p_age_tf = new javax.swing.JTextField();
        male_radio = new javax.swing.JRadioButton();
        female_radio = new javax.swing.JRadioButton();
        p_rating_tf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pm_issue_tf = new javax.swing.JTextField();
        insert_btn = new javax.swing.JButton();
        refresh_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        pos_combo1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        p_weight_tf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        p_height_tf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        p_nation_tf = new javax.swing.JTextField();
        srch_p_name = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        pi = new javax.swing.JLabel();
        ps = new javax.swing.JLabel();
        cy = new javax.swing.JLabel();
        pv = new javax.swing.JLabel();
        p_salary_tf = new javax.swing.JTextField();
        con_left_tf = new javax.swing.JTextField();
        p_bonus_tf = new javax.swing.JTextField();
        pi1 = new javax.swing.JLabel();
        cy1 = new javax.swing.JLabel();
        p_leave_tf = new javax.swing.JTextField();
        med_des_tf = new javax.swing.JTextField();
        pv1 = new javax.swing.JLabel();
        up_salary = new javax.swing.JTextField();
        up_ms = new javax.swing.JTextField();
        p_pay_id_tf = new javax.swing.JLabel();
        p_med_id_tf = new javax.swing.JLabel();
        img_l = new javax.swing.JLabel();
        ch_btn = new javax.swing.JButton();
        val_l = new javax.swing.JLabel();
        val_l1 = new javax.swing.JLabel();
        srch_by_combo = new javax.swing.JComboBox<>();
        asc = new javax.swing.JLabel();
        desc = new javax.swing.JLabel();
        leave_date_d = new com.toedter.calendar.JDateChooser();
        injured_date_d = new com.toedter.calendar.JDateChooser();
        Injured_date_l = new javax.swing.JLabel();
        transfer_player = new javax.swing.JButton();
        srch_p_range_2 = new javax.swing.JTextField();
        srch_p_range_1 = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        leave_date_l = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 204));
        setMinimumSize(new java.awt.Dimension(1000, 470));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        player_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Position", "Age", "Sex", "Weight", "Height", "Nationality", "Rating", "Med Issue"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        player_jTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        player_jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player_jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(player_jTable);
        if (player_jTable.getColumnModel().getColumnCount() > 0) {
            player_jTable.getColumnModel().getColumn(0).setResizable(false);
            player_jTable.getColumnModel().getColumn(0).setPreferredWidth(35);
            player_jTable.getColumnModel().getColumn(1).setResizable(false);
            player_jTable.getColumnModel().getColumn(1).setPreferredWidth(150);
            player_jTable.getColumnModel().getColumn(2).setResizable(false);
            player_jTable.getColumnModel().getColumn(2).setPreferredWidth(80);
            player_jTable.getColumnModel().getColumn(3).setResizable(false);
            player_jTable.getColumnModel().getColumn(3).setPreferredWidth(45);
            player_jTable.getColumnModel().getColumn(4).setResizable(false);
            player_jTable.getColumnModel().getColumn(4).setPreferredWidth(70);
            player_jTable.getColumnModel().getColumn(5).setResizable(false);
            player_jTable.getColumnModel().getColumn(5).setPreferredWidth(70);
            player_jTable.getColumnModel().getColumn(6).setResizable(false);
            player_jTable.getColumnModel().getColumn(6).setPreferredWidth(70);
            player_jTable.getColumnModel().getColumn(7).setResizable(false);
            player_jTable.getColumnModel().getColumn(7).setPreferredWidth(150);
            player_jTable.getColumnModel().getColumn(8).setResizable(false);
            player_jTable.getColumnModel().getColumn(8).setPreferredWidth(70);
            player_jTable.getColumnModel().getColumn(9).setResizable(false);
            player_jTable.getColumnModel().getColumn(9).setPreferredWidth(100);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 675, 170));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Player");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Player Name:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        p_name_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_name_tfActionPerformed(evt);
            }
        });
        getContentPane().add(p_name_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 167, -1));

        pos_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GoalKeeper", "Defender", "Midfielder", "Forward" }));
        pos_combo.setBorder(null);
        pos_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos_comboActionPerformed(evt);
            }
        });
        getContentPane().add(pos_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 100, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Position:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 60, -1));

        back_btn1.setText("Back");
        back_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(back_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Age:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 30, -1));

        p_age_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_age_tfActionPerformed(evt);
            }
        });
        getContentPane().add(p_age_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 155, 60, -1));

        male_radio.setForeground(new java.awt.Color(255, 255, 255));
        male_radio.setText("Male");
        male_radio.setBorder(null);
        male_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                male_radioActionPerformed(evt);
            }
        });
        getContentPane().add(male_radio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 193, -1, 20));

        female_radio.setForeground(new java.awt.Color(255, 255, 255));
        female_radio.setText("Female");
        female_radio.setBorder(null);
        female_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                female_radioActionPerformed(evt);
            }
        });
        getContentPane().add(female_radio, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 193, -1, 20));

        p_rating_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_rating_tfActionPerformed(evt);
            }
        });
        getContentPane().add(p_rating_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 50, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Rating:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Medical Issue:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        pm_issue_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pm_issue_tfActionPerformed(evt);
            }
        });
        getContentPane().add(pm_issue_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 169, -1));

        insert_btn.setText("Insert");
        insert_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_btnActionPerformed(evt);
            }
        });
        getContentPane().add(insert_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        refresh_btn.setText("Refresh");
        refresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_btnActionPerformed(evt);
            }
        });
        getContentPane().add(refresh_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, -1, -1));

        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        getContentPane().add(update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, -1, -1));

        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        getContentPane().add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, -1, -1));

        clear_btn.setText("Clear");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });
        getContentPane().add(clear_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        pos_combo1.setBorder(null);
        pos_combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos_combo1ActionPerformed(evt);
            }
        });
        getContentPane().add(pos_combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 60, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sex:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Weight:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, 20));

        p_weight_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_weight_tfActionPerformed(evt);
            }
        });
        getContentPane().add(p_weight_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 50, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Height:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, 20));

        p_height_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_height_tfActionPerformed(evt);
            }
        });
        getContentPane().add(p_height_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 50, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nationality:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        p_nation_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_nation_tfActionPerformed(evt);
            }
        });
        getContentPane().add(p_nation_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 166, -1));

        srch_p_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srch_p_nameActionPerformed(evt);
            }
        });
        srch_p_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srch_p_nameKeyReleased(evt);
            }
        });
        getContentPane().add(srch_p_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 130, 25));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Search By");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, 20));

        pi.setForeground(new java.awt.Color(255, 255, 255));
        pi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pi.setText("Paying Id");
        getContentPane().add(pi, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 50, -1));

        ps.setForeground(new java.awt.Color(255, 255, 255));
        ps.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ps.setText("Player Salary");
        getContentPane().add(ps, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 120, -1));

        cy.setForeground(new java.awt.Color(255, 255, 255));
        cy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cy.setText("Contract Left (Months)");
        getContentPane().add(cy, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, -1, -1));

        pv.setForeground(new java.awt.Color(255, 255, 255));
        pv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pv.setText("Performance Bonus");
        getContentPane().add(pv, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 120, -1));

        p_salary_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(p_salary_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 120, -1));

        con_left_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(con_left_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 110, -1));

        p_bonus_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p_bonus_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_bonus_tfActionPerformed(evt);
            }
        });
        getContentPane().add(p_bonus_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 120, -1));

        pi1.setForeground(new java.awt.Color(255, 255, 255));
        pi1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pi1.setText("Medical Id");
        getContentPane().add(pi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 55, -1));

        cy1.setForeground(new java.awt.Color(255, 255, 255));
        cy1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cy1.setText("Leave Left (Days)");
        getContentPane().add(cy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, -1));

        p_leave_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(p_leave_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 64, -1));

        med_des_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(med_des_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 172, -1));

        pv1.setForeground(new java.awt.Color(255, 255, 255));
        pv1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pv1.setText("Description");
        getContentPane().add(pv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 120, -1));

        up_salary.setBackground(new java.awt.Color(240, 240, 240));
        up_salary.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        up_salary.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        up_salary.setText("Update");
        up_salary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                up_salaryMouseClicked(evt);
            }
        });
        up_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_salaryActionPerformed(evt);
            }
        });
        getContentPane().add(up_salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, -1, -1));

        up_ms.setBackground(new java.awt.Color(240, 240, 240));
        up_ms.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        up_ms.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        up_ms.setText("Update");
        up_ms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                up_msMouseClicked(evt);
            }
        });
        up_ms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_msActionPerformed(evt);
            }
        });
        getContentPane().add(up_ms, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, -1, -1));

        p_pay_id_tf.setForeground(new java.awt.Color(255, 255, 255));
        p_pay_id_tf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(p_pay_id_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 50, 20));

        p_med_id_tf.setForeground(new java.awt.Color(255, 255, 255));
        p_med_id_tf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(p_med_id_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 55, 20));

        img_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img_l.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(img_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 290, 120, 140));

        ch_btn.setText("Change");
        ch_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch_btnActionPerformed(evt);
            }
        });
        getContentPane().add(ch_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 440, -1, -1));

        val_l.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        val_l.setForeground(new java.awt.Color(153, 0, 0));
        val_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(val_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 441, 232, 23));

        val_l1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        val_l1.setForeground(new java.awt.Color(153, 0, 0));
        val_l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(val_l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 441, 250, 23));

        srch_by_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "Possition", "Age", "Sex", "Weight", "Height", "Nationality", "Rating", "Med Issue" }));
        srch_by_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srch_by_comboActionPerformed(evt);
            }
        });
        getContentPane().add(srch_by_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 110, -1));

        asc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/image/up_d.png"))); // NOI18N
        asc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        asc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ascMouseClicked(evt);
            }
        });
        getContentPane().add(asc, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 20, 20));

        desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/image/down_d .png"))); // NOI18N
        desc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descMouseClicked(evt);
            }
        });
        getContentPane().add(desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 20, 20));
        getContentPane().add(leave_date_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 130, -1));
        getContentPane().add(injured_date_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 130, -1));

        Injured_date_l.setForeground(new java.awt.Color(255, 255, 255));
        Injured_date_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Injured_date_l.setText("Injured Date");
        getContentPane().add(Injured_date_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, -1, 20));

        transfer_player.setText("Transfer Player");
        transfer_player.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transfer_playerActionPerformed(evt);
            }
        });
        getContentPane().add(transfer_player, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, -1, -1));

        srch_p_range_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srch_p_range_2ActionPerformed(evt);
            }
        });
        srch_p_range_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srch_p_range_2KeyReleased(evt);
            }
        });
        getContentPane().add(srch_p_range_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 60, 25));

        srch_p_range_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srch_p_range_1ActionPerformed(evt);
            }
        });
        srch_p_range_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srch_p_range_1KeyReleased(evt);
            }
        });
        getContentPane().add(srch_p_range_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 60, 25));

        ok.setText("Ok");
        ok.setAlignmentY(0.0F);
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, -1, -1));

        leave_date_l.setForeground(new java.awt.Color(255, 255, 255));
        leave_date_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leave_date_l.setText("Releasing Date");
        getContentPane().add(leave_date_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Staffs/gg.png"))); // NOI18N
        jLabel3.setIconTextGap(0);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 505));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void player_jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player_jTableMouseClicked
        // TODO add your handling code here:
        int i = player_jTable.getSelectedRow();
        TableModel model = player_jTable.getModel();

        //String id_img = model.getValueAt(i, 0).toString();
        p_name_tf.setText(model.getValueAt(i, 1).toString());

        String pos = model.getValueAt(i, 2).toString();
        switch (pos) {
            case "GK":
                pos_combo.setSelectedIndex(0);
                pos_combo1.setSelectedIndex(0);
                break;
            case "CB":
                //
                pos_combo.setSelectedIndex(1);
                pos_combo1.setSelectedIndex(0);
                break;
            case "LB":
                //
                pos_combo.setSelectedIndex(1);
                pos_combo1.setSelectedIndex(1);
                break;
            case "RB":
                //
                pos_combo.setSelectedIndex(1);
                pos_combo1.setSelectedIndex(2);
                break;
            case "DMF":
                //
                pos_combo.setSelectedIndex(2);
                pos_combo1.setSelectedIndex(0);
                break;
            case "CMF":
                //
                pos_combo.setSelectedIndex(2);
                pos_combo1.setSelectedIndex(1);
                break;
            case "LMF":
                //
                pos_combo.setSelectedIndex(2);
                pos_combo1.setSelectedIndex(2);
                break;
            case "RMF":
                //
                pos_combo.setSelectedIndex(2);
                pos_combo1.setSelectedIndex(3);
                break;
            case "AMF":
                //
                pos_combo.setSelectedIndex(2);
                pos_combo1.setSelectedIndex(4);
                break;
            case "LWF":
                //
                pos_combo.setSelectedIndex(3);
                pos_combo1.setSelectedIndex(0);
                break;
            case "RWF":
                //
                pos_combo.setSelectedIndex(3);
                pos_combo1.setSelectedIndex(1);
                break;
            case "SS":
                //
                pos_combo.setSelectedIndex(3);
                pos_combo1.setSelectedIndex(2);
                break;
            case "CF":
                //
                pos_combo.setSelectedIndex(3);
                pos_combo1.setSelectedIndex(3);
        }

        p_age_tf.setText(model.getValueAt(i, 3).toString());

        String area = model.getValueAt(i, 4).toString();
        if (area.equalsIgnoreCase("Male")) {
            male_radio.setSelected(true);
            female_radio.setSelected(false);
        }
        if (area.equalsIgnoreCase("Female")) {
            female_radio.setSelected(true);
            male_radio.setSelected(false);
        }
        p_weight_tf.setText(model.getValueAt(i, 5).toString());

        p_height_tf.setText(model.getValueAt(i, 6).toString());

        p_nation_tf.setText(model.getValueAt(i, 7).toString());

        p_rating_tf.setText(model.getValueAt(i, 8).toString());

        pm_issue_tf.setText(model.getValueAt(i, 9).toString());

        visibility_true();

        p_salary();

        p_med_sts();

        try {
            byte[] img = (userList().get(i).getpImg());
            ImageIcon img_ic = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(img_l.getWidth(), img_l.getHeight(), Image.SCALE_SMOOTH));
            img_l.setIcon(img_ic);

        } catch (Exception e) {
            clr_data();
            System.out.println(e);
        }


    }//GEN-LAST:event_player_jTableMouseClicked

    private void p_name_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_name_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_name_tfActionPerformed

    private void pos_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos_comboActionPerformed
        // TODO add your handling code here:
        try {
            if (pos_combo.getSelectedItem().equals("GoalKeeper")) {
                pos_combo1.removeAllItems();
                pos_combo1.addItem("GK");
                pos_combo1.setSelectedItem(null);
            } else if (pos_combo.getSelectedItem().equals("Defender")) {
                pos_combo1.removeAllItems();
                pos_combo1.addItem("CB");
                pos_combo1.addItem("LB");
                pos_combo1.addItem("RB");
                pos_combo1.setSelectedItem(null);
            } else if (pos_combo.getSelectedItem().equals("Midfielder")) {
                pos_combo1.removeAllItems();
                pos_combo1.addItem("DMF");
                pos_combo1.addItem("CMF");
                pos_combo1.addItem("LMF");
                pos_combo1.addItem("RMF");
                pos_combo1.addItem("AMF");
                pos_combo1.setSelectedItem(null);
            } else if (pos_combo.getSelectedItem().equals("Forward")) {
                pos_combo1.removeAllItems();
                pos_combo1.addItem("LWF");
                pos_combo1.addItem("RWF");
                pos_combo1.addItem("SS");
                pos_combo1.addItem("CF");
                pos_combo1.setSelectedItem(null);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_pos_comboActionPerformed

    private void back_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btn1ActionPerformed
        // TODO add your handling code here:
        window field = new window();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_back_btn1ActionPerformed

    private void p_age_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_age_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_age_tfActionPerformed

    private void male_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_male_radioActionPerformed
        // TODO add your handling code here:
        if (male_radio.isSelected()) {
            female_radio.setSelected(false);
        }
    }//GEN-LAST:event_male_radioActionPerformed

    private void female_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_female_radioActionPerformed
        // TODO add your handling code here:
        if (female_radio.isSelected()) {
            male_radio.setSelected(false);
        }
    }//GEN-LAST:event_female_radioActionPerformed

    private void p_rating_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_rating_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_rating_tfActionPerformed

    private void pm_issue_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pm_issue_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pm_issue_tfActionPerformed

    public void clear() {
        srch_p_range_1.setText("");
        srch_p_range_2.setText("");
        p_name_tf.setText("");
        pos_combo.setSelectedIndex(-1);
        pos_combo1.setSelectedIndex(-1);
        p_age_tf.setText("");
        male_radio.setSelected(false);
        female_radio.setSelected(false);
        p_weight_tf.setText("");
        p_height_tf.setText("");
        p_nation_tf.setText("");
        p_rating_tf.setText("");
        pm_issue_tf.setText("");

        clr_data();
        visibility_false();
        img_l.setIcon(null);
    }

    private void insert_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_btnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Choose a Photo for Player");
        image_choose();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            String query = "insert into Player(P_NAME ,P_POSSITION ,P_AGE ,P_SEX ,P_WEIGHT ,P_HEIGHT ,P_Nationality ,P_RATING ,P_M_issue, P_Image)values(?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, p_name_tf.getText());
            String m_result;
            m_result = pos_combo1.getSelectedItem().toString();
            pst.setString(2, m_result);
            pst.setString(3, p_age_tf.getText());
            if (male_radio.isSelected()) {
                m_area = "Male";
            }
            if (female_radio.isSelected()) {
                m_area = "Female";
            }
            pst.setString(4, m_area);
            pst.setString(5, p_weight_tf.getText());
            pst.setString(6, p_height_tf.getText());
            pst.setString(7, p_nation_tf.getText());
            pst.setString(8, p_rating_tf.getText());
            pst.setString(9, pm_issue_tf.getText());
            pst.setBytes(10, plr_img);

            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) player_jTable.getModel();
            model.setRowCount(0);
            show_player();

            clear();

            player_salary ps = new player_salary();
            ps.setVisible(true);

            //JOptionPane.showMessageDialog(null, "Inserted Sucessfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_insert_btnActionPerformed

    private void refresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_btnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) player_jTable.getModel();
        model.setRowCount(0);
        show_player();
    }//GEN-LAST:event_refresh_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure to Delete?", "Delete", JOptionPane.YES_NO_CANCEL_OPTION);
        if (confirm == 0) {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
                Connection con = DriverManager.getConnection(url);
                int row = player_jTable.getSelectedRow();
                String value = (player_jTable.getModel().getValueAt(row, 0).toString());

                String med = "Delete from [Player Salary] where P_ID IN (Select P_ID from Player where P_ID =" + value + ")";
                PreparedStatement med_pst = con.prepareStatement(med);
                med_pst.executeUpdate();

                String sal = "Delete from [Player Medical Status] where P_ID IN (Select P_ID from Player where P_ID =" + value + ")";
                PreparedStatement sal_pst = con.prepareStatement(sal);
                sal_pst.executeUpdate();

                clr_data();

                String query = "Delete from Player where P_ID =" + value;
                PreparedStatement pst = con.prepareStatement(query);
                pst.executeUpdate();

                DefaultTableModel model = (DefaultTableModel) player_jTable.getModel();
                model.setRowCount(0);
                show_player();

                clear();

                JOptionPane.showMessageDialog(null, "Deleted Sucessfully!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:
        clear();

    }//GEN-LAST:event_clear_btnActionPerformed

    private void pos_combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos_combo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pos_combo1ActionPerformed

    private void p_weight_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_weight_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_weight_tfActionPerformed

    private void p_height_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_height_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_height_tfActionPerformed

    private void p_nation_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_nation_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_nation_tfActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            int row = player_jTable.getSelectedRow();
            String value = (player_jTable.getModel().getValueAt(row, 0).toString());
            String query = "Update Player SET P_NAME = ? ,P_POSSITION = ? ,P_AGE = ? ,P_SEX = ? ,P_WEIGHT = ? ,P_HEIGHT = ?,P_Nationality = ? ,P_RATING = ?,P_M_issue = ?, P_Image = ? where P_ID =" + value;
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, p_name_tf.getText());
            String m_result;
            m_result = pos_combo1.getSelectedItem().toString();
            pst.setString(2, m_result);
            pst.setString(3, p_age_tf.getText());
            if (male_radio.isSelected()) {
                m_area = "Male";
            }
            if (female_radio.isSelected()) {
                m_area = "Female";
            }
            pst.setString(4, m_area);
            pst.setString(5, p_weight_tf.getText());
            pst.setString(6, p_height_tf.getText());
            pst.setString(7, p_nation_tf.getText());
            pst.setString(8, p_rating_tf.getText());
            pst.setString(9, pm_issue_tf.getText());
            pst.setBytes(10, plr_img);

            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) player_jTable.getModel();
            model.setRowCount(0);
            show_player();

            clear();

            JOptionPane.showMessageDialog(null, "Updated Sucessfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_update_btnActionPerformed

    private void srch_p_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srch_p_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srch_p_nameActionPerformed
    public void srch_combo_logic() {
        try {
            if (srch_by_combo.getSelectedItem().equals("Name")) {
                srch_by_com = "P_Name";
            } else if (srch_by_combo.getSelectedItem().equals("Possition")) {
                srch_by_com = "P_Possition";
            } else if (srch_by_combo.getSelectedItem().equals("Age")) {
                srch_by_com = "P_Age";
            } else if (srch_by_combo.getSelectedItem().equals("Sex")) {
                srch_by_com = "P_Sex";
            } else if (srch_by_combo.getSelectedItem().equals("Weight")) {
                srch_by_com = "P_Weight";
            } else if (srch_by_combo.getSelectedItem().equals("Height")) {
                srch_by_com = "P_Height";
            } else if (srch_by_combo.getSelectedItem().equals("Nationality")) {
                srch_by_com = "P_Nationality";
            } else if (srch_by_combo.getSelectedItem().equals("Rating")) {
                srch_by_com = "P_Rating";
            } else if (srch_by_combo.getSelectedItem().equals("Med Issue")) {
                srch_by_com = "P_M_Issue";
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    public String srch_by_com;
    private void srch_p_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srch_p_nameKeyReleased
        // TODO add your handling code here:
        srch_combo_logic();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);

            TableModel model = player_jTable.getModel();

            String value = srch_p_name.getText();
            String srch_by = srch_by_com.toString();
            String query = "Select [P_ID]\n"
                    + "      ,[P_NAME]\n"
                    + "      ,[P_POSSITION]\n"
                    + "      ,[P_AGE]\n"
                    + "      ,[P_SEX]\n"
                    + "      ,[P_WEIGHT]\n"
                    + "      ,[P_HEIGHT]\n"
                    + "      ,[P_Nationality]\n"
                    + "      ,[P_RATING]\n"
                    + "      ,[P_M_issue] from Player "
                    + " where " + srch_by + " LIKE '%" + value + "%'";
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            player_jTable.setModel(DbUtils.resultSetToTableModel(rs));

            /*if (rs.next()) {
                String setname = rs.getString("p_name");
                p_name_tf.setText(setname);

                String setpos = rs.getString("P_POSSITION");
                switch (setpos) {
                    case "GK":
                        pos_combo.setSelectedIndex(0);
                        pos_combo1.setSelectedIndex(0);
                        break;
                    case "CB":
                        //
                        pos_combo.setSelectedIndex(1);
                        pos_combo1.setSelectedIndex(0);
                        break;
                    case "LB":
                        //
                        pos_combo.setSelectedIndex(1);
                        pos_combo1.setSelectedIndex(1);
                        break;
                    case "RB":
                        //
                        pos_combo.setSelectedIndex(1);
                        pos_combo1.setSelectedIndex(2);
                        break;
                    case "DMF":
                        //
                        pos_combo.setSelectedIndex(2);
                        pos_combo1.setSelectedIndex(0);
                        break;
                    case "CMF":
                        //
                        pos_combo.setSelectedIndex(2);
                        pos_combo1.setSelectedIndex(1);
                        break;
                    case "LMF":
                        //
                        pos_combo.setSelectedIndex(2);
                        pos_combo1.setSelectedIndex(2);
                        break;
                    case "RMF":
                        //
                        pos_combo.setSelectedIndex(2);
                        pos_combo1.setSelectedIndex(3);
                        break;
                    case "AMF":
                        //
                        pos_combo.setSelectedIndex(2);
                        pos_combo1.setSelectedIndex(4);
                        break;
                    case "LWF":
                        //
                        pos_combo.setSelectedIndex(3);
                        pos_combo1.setSelectedIndex(0);
                        break;
                    case "RWF":
                        //
                        pos_combo.setSelectedIndex(3);
                        pos_combo1.setSelectedIndex(1);
                        break;
                    case "SS":
                        //
                        pos_combo.setSelectedIndex(3);
                        pos_combo1.setSelectedIndex(2);
                        break;
                    case "CF":
                        //
                        pos_combo.setSelectedIndex(3);
                        pos_combo1.setSelectedIndex(3);
                }

                int setage = rs.getInt("p_age");
                String seta = String.valueOf(setage);
                p_age_tf.setText(seta);

                String setSex = rs.getString("p_sex");
                if (setSex.equalsIgnoreCase("Male")) {
                    male_radio.setSelected(true);
                    female_radio.setSelected(false);
                }
                if (setSex.equalsIgnoreCase("Female")) {
                    female_radio.setSelected(true);
                    male_radio.setSelected(false);
                }
                int setW = rs.getInt("p_weight");
                String setw = String.valueOf(setW);
                p_weight_tf.setText(setw);

                int setH = rs.getInt("p_height");
                String seth = String.valueOf(setH);
                p_height_tf.setText(seth);

                String setnation = rs.getString("p_nationality");
                p_nation_tf.setText(setnation);

                int setR = rs.getInt("p_rating");
                String setr = String.valueOf(setR);
                p_rating_tf.setText(setr);

                String setM = rs.getString("p_m_issue");
                pm_issue_tf.setText(setM);
                
            }*/
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_srch_p_nameKeyReleased

    public void image_choose() {
        JFileChooser choose = new JFileChooser();
        choose.showOpenDialog(null);
        File f = choose.getSelectedFile();
        fileName = f.getAbsolutePath();
        ImageIcon img_ic = new ImageIcon(new ImageIcon(fileName).getImage().getScaledInstance(img_l.getWidth(), img_l.getHeight(), Image.SCALE_SMOOTH));
        img_l.setIcon(img_ic);
        try {
            File image = new File(fileName);
            FileInputStream fi = new FileInputStream(image);
            ByteArrayOutputStream aos = new ByteArrayOutputStream();
            byte[] te = new byte[1024];
            for (int rn; (rn = fi.read(te)) != -1;) {
                aos.write(te, 0, rn);
            }
            plr_img = aos.toByteArray();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void ch_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch_btnActionPerformed
        // TODO add your handling code here:
        image_choose();
    }//GEN-LAST:event_ch_btnActionPerformed

    private void up_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_salaryActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_up_salaryActionPerformed

    private void up_msActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_msActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_msActionPerformed

    private void up_salaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_up_salaryMouseClicked
        // TODO add your handling code here:
        Date da = (Date) leave_date_d.getDate();
        SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
        String l_date = dt.format(da);
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            int row = player_jTable.getSelectedRow();
            String value = p_pay_id_tf.getText().toString();
            String query = "Update [Player Salary] SET P_salary = ? ,leaving_date = ?, P_bonus = ? where P_PAY_ID =" + value;
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, p_salary_tf.getText());
            pst.setString(2, l_date);
            pst.setString(3, p_bonus_tf.getText());

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Updated Sucessfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_up_salaryMouseClicked

    private void up_msMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_up_msMouseClicked
        // TODO add your handling code here:
        Date da = (Date) injured_date_d.getDate();
        SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
        String i_date = dt.format(da);
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            int row = player_jTable.getSelectedRow();
            String value = p_med_id_tf.getText().toString();
            String query = "Update [Player Medical Status] SET LEAVE = ? ,M_Description = ? , Injured_date = ? where P_MED_ID = " + value;
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, p_leave_tf.getText());
            pst.setString(2, med_des_tf.getText());
            pst.setString(3, i_date);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Updated Sucessfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_up_msMouseClicked

    private void ascMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ascMouseClicked
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);

            TableModel model = player_jTable.getModel();

            String value = srch_p_name.getText();
            String srch_by = srch_by_com.toString();
            String query = "Select P_ID,P_NAME,P_POSSITION,P_AGE,P_SEX,P_WEIGHT,P_HEIGHT,P_Nationality,P_RATING,P_M_issue from Player "
                    + " where " + srch_by + " LIKE '%" + value + "%' order by " + srch_by + " asc ";
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            player_jTable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_ascMouseClicked

    private void descMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descMouseClicked
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);

            TableModel model = player_jTable.getModel();

            String value = srch_p_name.getText();
            String srch_by = srch_by_com.toString();
            String query = "Select P_ID,P_NAME,P_POSSITION,P_AGE,P_SEX,P_WEIGHT,P_HEIGHT,P_Nationality,P_RATING,P_M_issue from Player "
                    + " where " + srch_by + " LIKE '%" + value + "%' order by " + srch_by + " desc ";
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            player_jTable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_descMouseClicked

    private void srch_by_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srch_by_comboActionPerformed
        // TODO add your handling code here:
        srch_combo_logic();
    }//GEN-LAST:event_srch_by_comboActionPerformed

    private void transfer_playerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transfer_playerActionPerformed
        // TODO add your handling code here:
        p_transfer();
        JOptionPane.showMessageDialog(null, "Player ShortListed For Transfer");
    }//GEN-LAST:event_transfer_playerActionPerformed

    private void srch_p_range_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srch_p_range_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srch_p_range_2ActionPerformed

    private void srch_p_range_2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srch_p_range_2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_srch_p_range_2KeyReleased

    private void srch_p_range_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srch_p_range_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srch_p_range_1ActionPerformed

    private void srch_p_range_1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srch_p_range_1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_srch_p_range_1KeyReleased

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);

            TableModel model = player_jTable.getModel();

            String value1 = srch_p_range_1.getText().trim();
            String value2 = srch_p_range_2.getText().trim();
            String srch_by = srch_by_com.toString();
            String query = "Select P_ID,P_NAME,P_POSSITION,P_AGE,P_SEX,P_WEIGHT,P_HEIGHT,P_Nationality,P_RATING,P_M_issue from Player "
                    + " where " + srch_by + " BETWEEN " + value1 + " AND " + value2 + " order by " + srch_by;
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            player_jTable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_okActionPerformed

    private void p_bonus_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_bonus_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_bonus_tfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(p_player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(p_player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(p_player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(p_player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new p_player().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Injured_date_l;
    private javax.swing.JLabel asc;
    private javax.swing.JButton back_btn1;
    private javax.swing.JButton ch_btn;
    private javax.swing.JButton clear_btn;
    private javax.swing.JTextField con_left_tf;
    private javax.swing.JLabel cy;
    private javax.swing.JLabel cy1;
    private javax.swing.JButton delete_btn;
    private javax.swing.JLabel desc;
    private javax.swing.JRadioButton female_radio;
    private javax.swing.JLabel img_l;
    private com.toedter.calendar.JDateChooser injured_date_d;
    private javax.swing.JButton insert_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser leave_date_d;
    private javax.swing.JLabel leave_date_l;
    private javax.swing.JRadioButton male_radio;
    private javax.swing.JTextField med_des_tf;
    private javax.swing.JButton ok;
    private javax.swing.JTextField p_age_tf;
    private javax.swing.JTextField p_bonus_tf;
    private javax.swing.JTextField p_height_tf;
    private javax.swing.JTextField p_leave_tf;
    private javax.swing.JLabel p_med_id_tf;
    private javax.swing.JTextField p_name_tf;
    private javax.swing.JTextField p_nation_tf;
    private javax.swing.JLabel p_pay_id_tf;
    private javax.swing.JTextField p_rating_tf;
    private javax.swing.JTextField p_salary_tf;
    private javax.swing.JTextField p_weight_tf;
    private javax.swing.JLabel pi;
    private javax.swing.JLabel pi1;
    private javax.swing.JTable player_jTable;
    private javax.swing.JTextField pm_issue_tf;
    private javax.swing.JComboBox<String> pos_combo;
    private javax.swing.JComboBox<String> pos_combo1;
    private javax.swing.JLabel ps;
    private javax.swing.JLabel pv;
    private javax.swing.JLabel pv1;
    private javax.swing.JButton refresh_btn;
    private javax.swing.JComboBox<String> srch_by_combo;
    private javax.swing.JTextField srch_p_name;
    private javax.swing.JTextField srch_p_range_1;
    private javax.swing.JTextField srch_p_range_2;
    private javax.swing.JButton transfer_player;
    private javax.swing.JTextField up_ms;
    private javax.swing.JTextField up_salary;
    private javax.swing.JButton update_btn;
    private javax.swing.JLabel val_l;
    private javax.swing.JLabel val_l1;
    // End of variables declaration//GEN-END:variables
}
