package Staffs;

import Home.window;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author faisa
 */
public class staff extends javax.swing.JFrame {

    /**
     * Creates new form staff
     */
    String m_area;
    String fileName = null; 
    byte[] staff_img = null; 
    
     public void visibility_true(){
        p_id.setVisible(true);
        s_salary.setVisible(true);
        c_y.setVisible(true);
        s_b.setVisible(true);
        
        s_pay_id_tf.setVisible(true);
        s_salary_tf.setVisible(true);
        con_yr_tf.setVisible(true);
        s_bonus_tf.setVisible(true);
        
        m_id.setVisible(true);     
        leave.setVisible(true);
        description.setVisible(true);
        
        s_med_id_tf.setVisible(true);
        s_leave_tf.setVisible(true);
        s_med_des_tf.setVisible(true);
        
        up_salary.setVisible(true);
        up_ms.setVisible(true);
        ch_btn.setVisible(true);
        
        leave_date_l.setVisible(true);
        leave_date_d.setVisible(true);
        
        Injured_date_l.setVisible(true);
        injured_date_d.setVisible(true);
    }
    public void visibility_false(){
        
        p_id.setVisible(false);
        s_salary.setVisible(false);
        c_y.setVisible(false);
        s_b.setVisible(false);
        
        s_pay_id_tf.setVisible(false);
        s_salary_tf.setVisible(false);
        con_yr_tf.setVisible(false);
        s_bonus_tf.setVisible(false);
        
        m_id.setVisible(false);     
        leave.setVisible(false);
        description.setVisible(false);
        
        s_med_id_tf.setVisible(false);
        s_leave_tf.setVisible(false);
        s_med_des_tf.setVisible(false);
        
        up_salary.setVisible(false);
        up_ms.setVisible(false);
        ch_btn.setVisible(false);
        
        leave_date_l.setVisible(false);
        leave_date_d.setVisible(false);
        
        Injured_date_l.setVisible(false);
        injured_date_d.setVisible(false);
       
    }

    public staff() {
        initComponents();
        show_staff();
        
        visibility_false();
        
        Toolkit tk = getToolkit();
        Dimension size = tk.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public ArrayList<staff_user> userList() {
        ArrayList<staff_user> userslist = new ArrayList();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            String query1 = "SELECT * FROM Staff";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);

            while (rs.next()) {
                staff_user user = new staff_user(rs.getInt("s_id"), rs.getString("s_name"), rs.getString("s_type"), rs.getInt("s_age"), rs.getString("s_sex"), rs.getString("s_m_issue"),rs.getBytes("S_Image"));
                userslist.add(user);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return userslist;
    }

    public void show_staff() {
        ArrayList<staff_user> list = userList();
        DefaultTableModel model = (DefaultTableModel) staff_jTable.getModel();
        Object[] row = new Object[6];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getsId();
            row[1] = list.get(i).getsName();
            row[2] = list.get(i).getsType();
            row[3] = list.get(i).getsAge();
            row[4] = list.get(i).getsSex();
            row[5] = list.get(i).getsMIssue();
            model.addRow(row);
        }
    }
    
    public void S_salary(){
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            
            
            int row = staff_jTable.getSelectedRow();
            String value = (staff_jTable.getModel().getValueAt(row, 0).toString());
            String query_cl = "select S_PAY_ID,S_salary,leaving_date,S_bonus from Staff right join [Staff Salary] on Staff.S_ID  = [Staff Salary].s_ID  where  Staff.S_ID  = " + value;
            String con_left ="select (DATEDIFF(MM,GETDATE(),leaving_date)) as Months from [Staff Salary]where (GETDATE() <= leaving_date and s_id ="+ value +" )group by leaving_date order by Months";
            PreparedStatement pst = con.prepareStatement(query_cl);
            ResultSet rs = pst.executeQuery();
            
            PreparedStatement pst_left = con.prepareStatement(con_left);
            ResultSet rs_left = pst_left.executeQuery();
            
           /* pst.setString(1, p_pay_id_tf.getText());
            pst.setString(2, p_salary_tf.getText());
            pst.setString(3, con_yr_tf.getText());
            pst.setString(4, p_bonus_tf.getText());*/
            
            while (rs.next()) {
                
                s_pay_id_tf.setText(rs.getString(1));

                s_salary_tf.setText(rs.getString(2));

                leave_date_d.setDate(rs.getDate(3));

                s_bonus_tf.setText(rs.getString(4));
            }
            
            while (rs_left.next()) {
                con_yr_tf.setText(rs_left.getString(1));
            }
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
     public void s_med_sts(){
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            
            
            int row = staff_jTable.getSelectedRow();
            String value = (staff_jTable.getModel().getValueAt(row, 0).toString());
            String query_sl = "select S_MED_ID,LEAVE,M_Description,injured_date from Staff right join [Staff Medical Status] on Staff.S_ID = [Staff Medical Status].S_ID where Staff.S_ID = " +value;
            String Leave_left = " select (DATEDIFF(DD,GETDATE(),(DATEADD(DD,leave,Injured_date)))) as DDays from [staff Medical Status] where (GETDATE() >= Injured_date and s_ID = "+value+") group by Injured_date,LEAVE order by DDays";
            PreparedStatement pst = con.prepareStatement(query_sl);
            ResultSet rs = pst.executeQuery();
            
            PreparedStatement pst_left = con.prepareStatement(Leave_left);
            ResultSet rs_left = pst_left.executeQuery();
            
            
           /* pst.setString(1, p_pay_id_tf.getText());
            pst.setString(2, p_salary_tf.getText());
            pst.setString(3, con_yr_tf.getText());
            pst.setString(4, p_bonus_tf.getText());*/
            
            while (rs.next()) {
                
                s_med_id_tf.setText(rs.getString(1));
                
                s_leave_tf.setText(rs.getString(2));

                s_med_des_tf.setText(rs.getString(3));
                
                injured_date_d.setDate(rs.getDate(4));
                
            }
            while (rs_left.next()) {
                 s_leave_tf.setText(rs_left.getString(1));
            }
            
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        s_name_tf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        back_btn1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        s_age_tf = new javax.swing.JTextField();
        male_radio = new javax.swing.JRadioButton();
        female_radio = new javax.swing.JRadioButton();
        s_type_tf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        smissue_tf = new javax.swing.JTextField();
        insert_btn = new javax.swing.JButton();
        refresh_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        staff_jTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        srch_by_combo = new javax.swing.JComboBox<>();
        search_s_name = new javax.swing.JTextField();
        asc1 = new javax.swing.JLabel();
        desc = new javax.swing.JLabel();
        p_id = new javax.swing.JLabel();
        s_pay_id_tf = new javax.swing.JLabel();
        s_salary_tf = new javax.swing.JTextField();
        s_salary = new javax.swing.JLabel();
        con_yr_tf = new javax.swing.JTextField();
        c_y = new javax.swing.JLabel();
        s_b = new javax.swing.JLabel();
        s_bonus_tf = new javax.swing.JTextField();
        up_salary = new javax.swing.JTextField();
        leave_date_d = new com.toedter.calendar.JDateChooser();
        leave_date_l = new javax.swing.JLabel();
        m_id = new javax.swing.JLabel();
        leave = new javax.swing.JLabel();
        s_leave_tf = new javax.swing.JTextField();
        s_med_id_tf = new javax.swing.JLabel();
        Injured_date_l = new javax.swing.JLabel();
        injured_date_d = new com.toedter.calendar.JDateChooser();
        s_med_des_tf = new javax.swing.JTextField();
        description = new javax.swing.JLabel();
        up_ms = new javax.swing.JTextField();
        img_l = new javax.swing.JLabel();
        ch_btn = new javax.swing.JButton();
        srch_p_range_2 = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        srch_p_range_1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 505));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Staff");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 38, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Staff Name:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 116, -1, -1));

        s_name_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_name_tfActionPerformed(evt);
            }
        });
        getContentPane().add(s_name_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 113, 161, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Staff Type:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 154, -1, -1));

        back_btn1.setText("Back");
        back_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(back_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Age:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 189, -1, -1));

        s_age_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_age_tfActionPerformed(evt);
            }
        });
        getContentPane().add(s_age_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 60, -1));

        male_radio.setForeground(new java.awt.Color(255, 255, 255));
        male_radio.setText("Male");
        male_radio.setBorder(null);
        male_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                male_radioActionPerformed(evt);
            }
        });
        getContentPane().add(male_radio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, 20));

        female_radio.setForeground(new java.awt.Color(255, 255, 255));
        female_radio.setText("Female");
        female_radio.setBorder(null);
        female_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                female_radioActionPerformed(evt);
            }
        });
        getContentPane().add(female_radio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, 20));

        s_type_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_type_tfActionPerformed(evt);
            }
        });
        getContentPane().add(s_type_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 115, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Medical Issue:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        smissue_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smissue_tfActionPerformed(evt);
            }
        });
        getContentPane().add(smissue_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 161, -1));

        insert_btn.setText("Insert");
        insert_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_btnActionPerformed(evt);
            }
        });
        getContentPane().add(insert_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        refresh_btn.setText("Refresh");
        refresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_btnActionPerformed(evt);
            }
        });
        getContentPane().add(refresh_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        getContentPane().add(update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));

        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        getContentPane().add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));

        clear_btn.setText("Clear");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });
        getContentPane().add(clear_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        staff_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Staff ID", "Staff Name", "Staff Type", "Age", "Sex", "Medical Issue"
            }
        ));
        staff_jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staff_jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(staff_jTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 680, 140));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sex:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 224, -1, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Search By");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 20, -1, 32));

        srch_by_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "Type", "Age", "Sex", "Med issue", " " }));
        srch_by_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srch_by_comboActionPerformed(evt);
            }
        });
        getContentPane().add(srch_by_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 27, 110, -1));

        search_s_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_s_nameActionPerformed(evt);
            }
        });
        search_s_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_s_nameKeyReleased(evt);
            }
        });
        getContentPane().add(search_s_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 25, 160, 25));

        asc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asc1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/image/up_d.png"))); // NOI18N
        asc1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        asc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                asc1MouseClicked(evt);
            }
        });
        getContentPane().add(asc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(783, 30, 20, 20));

        desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/image/down_d .png"))); // NOI18N
        desc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descMouseClicked(evt);
            }
        });
        getContentPane().add(desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 30, 20, 20));

        p_id.setForeground(new java.awt.Color(255, 255, 255));
        p_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p_id.setText("Paying Id");
        getContentPane().add(p_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

        s_pay_id_tf.setForeground(new java.awt.Color(255, 255, 255));
        s_pay_id_tf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(s_pay_id_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 50, 20));

        s_salary_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(s_salary_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 120, -1));

        s_salary.setForeground(new java.awt.Color(255, 255, 255));
        s_salary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s_salary.setText("Staff Salary");
        getContentPane().add(s_salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 98, -1));

        con_yr_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        con_yr_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con_yr_tfActionPerformed(evt);
            }
        });
        getContentPane().add(con_yr_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 108, -1));

        c_y.setForeground(new java.awt.Color(255, 255, 255));
        c_y.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c_y.setText("Contract Left(Months)");
        getContentPane().add(c_y, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, -1, -1));

        s_b.setForeground(new java.awt.Color(255, 255, 255));
        s_b.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s_b.setText("Performance Bonus");
        getContentPane().add(s_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, -1, -1));

        s_bonus_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(s_bonus_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 110, -1));

        up_salary.setBackground(new java.awt.Color(240, 240, 240));
        up_salary.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        up_salary.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        up_salary.setText("Update");
        up_salary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                up_salaryMouseClicked(evt);
            }
        });
        up_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_salaryActionPerformed(evt);
            }
        });
        getContentPane().add(up_salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, -1, -1));
        getContentPane().add(leave_date_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 130, -1));

        leave_date_l.setForeground(new java.awt.Color(255, 255, 255));
        leave_date_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leave_date_l.setText("Releasing Date");
        getContentPane().add(leave_date_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, -1, 20));

        m_id.setForeground(new java.awt.Color(255, 255, 255));
        m_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m_id.setText("Medical Id");
        getContentPane().add(m_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 55, -1));

        leave.setForeground(new java.awt.Color(255, 255, 255));
        leave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leave.setText("Leave (Days)");
        getContentPane().add(leave, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, -1, 20));

        s_leave_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(s_leave_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 64, -1));

        s_med_id_tf.setForeground(new java.awt.Color(255, 255, 255));
        s_med_id_tf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(s_med_id_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 55, 20));

        Injured_date_l.setForeground(new java.awt.Color(255, 255, 255));
        Injured_date_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Injured_date_l.setText("Injured Date");
        getContentPane().add(Injured_date_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, -1, 20));
        getContentPane().add(injured_date_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 130, -1));

        s_med_des_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(s_med_des_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 186, -1));

        description.setForeground(new java.awt.Color(255, 255, 255));
        description.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        description.setText("Description");
        getContentPane().add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 120, -1));

        up_ms.setBackground(new java.awt.Color(240, 240, 240));
        up_ms.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        up_ms.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        up_ms.setText("Update");
        up_ms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                up_msMouseClicked(evt);
            }
        });
        up_ms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_msActionPerformed(evt);
            }
        });
        getContentPane().add(up_ms, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 440, -1, -1));

        img_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(img_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 280, 130, 150));

        ch_btn.setText("Change");
        ch_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch_btnActionPerformed(evt);
            }
        });
        getContentPane().add(ch_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 440, -1, -1));

        srch_p_range_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srch_p_range_2ActionPerformed(evt);
            }
        });
        srch_p_range_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srch_p_range_2KeyReleased(evt);
            }
        });
        getContentPane().add(srch_p_range_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 60, 25));

        ok.setText("Ok");
        ok.setAlignmentY(0.0F);
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, -1, -1));

        srch_p_range_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srch_p_range_1ActionPerformed(evt);
            }
        });
        srch_p_range_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srch_p_range_1KeyReleased(evt);
            }
        });
        getContentPane().add(srch_p_range_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 60, 25));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Staffs/gg.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 505));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void s_name_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_name_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_name_tfActionPerformed

    private void back_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btn1ActionPerformed
        // TODO add your handling code here:
        window field = new window();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_back_btn1ActionPerformed

    private void s_age_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_age_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_age_tfActionPerformed

    private void male_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_male_radioActionPerformed
        // TODO add your handling code here:
        if (male_radio.isSelected()) {
            female_radio.setSelected(false);
        }
    }//GEN-LAST:event_male_radioActionPerformed

    private void female_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_female_radioActionPerformed
        // TODO add your handling code here:
        if (female_radio.isSelected()) {
            male_radio.setSelected(false);
        }
    }//GEN-LAST:event_female_radioActionPerformed

    private void s_type_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_type_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_type_tfActionPerformed

    private void smissue_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smissue_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smissue_tfActionPerformed
    
    public void clr_data(){
            s_pay_id_tf.setText("");
            s_salary_tf.setText("");
            con_yr_tf.setText("");
            s_bonus_tf.setText("");            
        
            s_med_id_tf.setText("");
            s_leave_tf.setText("");
            s_med_des_tf.setText("");   
            
    }
    public void clear() {

        s_name_tf.setText("");
        s_type_tf.setText("");
        s_age_tf.setText("");
        male_radio.setSelected(false);
        female_radio.setSelected(false);
        smissue_tf.setText("");

        clr_data();
        visibility_false();
        img_l.setIcon(null);
    }
    
    private void insert_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_btnActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            String query = "insert into Staff(S_NAME,S_TYPE,S_AGE,S_SEX,S_M_issue)values(?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, s_name_tf.getText());
            pst.setString(2, s_type_tf.getText());
            pst.setString(3, s_age_tf.getText());
            if (male_radio.isSelected()) {
                m_area = "Male";
            }
            if (female_radio.isSelected()) {
                m_area = "Female";
            }
            pst.setString(4, m_area);
            pst.setString(5, smissue_tf.getText());

            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) staff_jTable.getModel();
            model.setRowCount(0);
            show_staff();

            JOptionPane.showMessageDialog(null, "Inserted Sucessfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_insert_btnActionPerformed

    private void refresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_btnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) staff_jTable.getModel();
        model.setRowCount(0);
        show_staff();
    }//GEN-LAST:event_refresh_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure to Delete?", "Delete", JOptionPane.YES_NO_CANCEL_OPTION);
        if (confirm == 0) {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
                Connection con = DriverManager.getConnection(url);
                int row = staff_jTable.getSelectedRow();
                String value = (staff_jTable.getModel().getValueAt(row, 0).toString());
                
                
                String med = "Delete from [Staff Salary] where S_ID IN (Select S_ID from Staff where S_ID ="+value+")";
                PreparedStatement med_pst = con.prepareStatement(med);
                med_pst.executeUpdate();
                
                String sal = "Delete from [Staff Medical Status] where S_ID IN (Select S_ID from Staff where S_ID ="+value+")";
                PreparedStatement sal_pst = con.prepareStatement(sal);
                sal_pst.executeUpdate();
                 clr_data();
                String query = "Delete from Staff where S_ID =" + value;
                PreparedStatement pst = con.prepareStatement(query);
                pst.executeUpdate();
                DefaultTableModel model = (DefaultTableModel) staff_jTable.getModel();
                model.setRowCount(0);
                show_staff();
                clear(); 

                JOptionPane.showMessageDialog(null, "Deleted Sucessfully!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:
        s_name_tf.setText("");
        s_type_tf.setText("");
        s_age_tf.setText("");
        male_radio.setSelected(false);
        female_radio.setSelected(false);
        smissue_tf.setText("");
        
        clr_data();
        visibility_false();
        img_l.setIcon(null);
    }//GEN-LAST:event_clear_btnActionPerformed

    private void staff_jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staff_jTableMouseClicked
        // TODO add your handling code here:
        int i = staff_jTable.getSelectedRow();
        TableModel model = staff_jTable.getModel();

        s_name_tf.setText(model.getValueAt(i, 1).toString());

        s_type_tf.setText(model.getValueAt(i, 2).toString());

        s_age_tf.setText(model.getValueAt(i, 3).toString());

        String area = model.getValueAt(i, 4).toString();
        if (area.equalsIgnoreCase("Male")) {
            male_radio.setSelected(true);
            female_radio.setSelected(false);
        }
        if (area.equalsIgnoreCase("Female")) {
            female_radio.setSelected(true);
            male_radio.setSelected(false);
        }

        smissue_tf.setText(model.getValueAt(i, 5).toString());
        
        S_salary();
        
        s_med_sts();
        visibility_true();
        
        try {
            byte[] img = (userList().get(i).getsImg());
            ImageIcon img_ic = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(img_l.getWidth(), img_l.getHeight(), Image.SCALE_SMOOTH));
            img_l.setIcon(img_ic);
           
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_staff_jTableMouseClicked

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            int row = staff_jTable.getSelectedRow();
            String value = (staff_jTable.getModel().getValueAt(row, 0).toString());
            String query = "Update Staff SET S_NAME = ? ,S_TYPE = ? ,S_AGE = ? ,S_SEX = ? ,S_M_issue = ?,S_image= ? where S_ID =" + value;
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, s_name_tf.getText());
//            String m_result;
//            m_result = pos_combo1.getSelectedItem().toString();
//            pst.setString(2, m_result);
//            pst.setString(3, p_age_tf.getText());
            if (male_radio.isSelected()) {
                m_area = "Male";
            }
            if (female_radio.isSelected()) {
                m_area = "Female";
            }
            pst.setString(2,s_type_tf.getText());
            pst.setString(3, s_age_tf.getText());
             pst.setString(4, m_area);
            pst.setString(5, smissue_tf.getText());
            pst.setBytes(6, staff_img);
//            pst.setString(7, p_nation_tf.getText());
//            pst.setString(8, p_rating_tf.getText());
//            pst.setString(9, pm_issue_tf.getText());

            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) staff_jTable.getModel();
            model.setRowCount(0);
            show_staff();
            clear();

            JOptionPane.showMessageDialog(null, "Updated Sucessfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_update_btnActionPerformed

    private void srch_by_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srch_by_comboActionPerformed
        // TODO add your handling code here:
        srch_combo_logic();
    }//GEN-LAST:event_srch_by_comboActionPerformed

    private void search_s_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_s_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_s_nameActionPerformed
    public String srch_by_com;
     
     public void srch_combo_logic(){
        try {
            if (srch_by_combo.getSelectedItem().equals("Name")) {
                srch_by_com = "s_Name";
            } else if(srch_by_combo.getSelectedItem().equals("Type")) {
                srch_by_com = "s_Type";
            } else if(srch_by_combo.getSelectedItem().equals("Age")) {
                srch_by_com = "s_Age";
            } else if(srch_by_combo.getSelectedItem().equals("Sex")) {
                srch_by_com = "s_Sex";
            } else if(srch_by_combo.getSelectedItem().equals("Med Issue")) {
                srch_by_com = "s_M_Issue";
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    } 
    
    private void search_s_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_s_nameKeyReleased
        // TODO add your handling code here:
        srch_combo_logic();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);

            TableModel model = staff_jTable.getModel();

            String value = search_s_name.getText();
            String search_by = srch_by_com.toString();
            String query = "Select S_ID,S_NAME, S_TYPE,S_AGE,S_SEX,S_M_issue from Staff "
                    + " where " + search_by + " LIKE '%"  + value + "%'";
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            staff_jTable.setModel(DbUtils.resultSetToTableModel(rs));
            
              
            } catch (Exception e) {                                                                                 
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_search_s_nameKeyReleased

    private void asc1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asc1MouseClicked
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);

            TableModel model =staff_jTable.getModel();

            String value = search_s_name.getText();
            String srch_by = srch_by_com.toString();
            String query = "Select S_ID,S_NAME,S_TYPE,S_AGE,S_SEX,S_M_issue from Staff "
            + " where " + srch_by + " LIKE '%"  + value + "%' order by " + srch_by + " asc ";
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            staff_jTable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_asc1MouseClicked

    private void descMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descMouseClicked
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);

            TableModel model = staff_jTable.getModel();

            String value = search_s_name.getText();
            String srch_by = srch_by_com.toString();
            String query = "Select S_ID,S_NAME,S_TYPE,S_AGE,S_SEX,S_M_issue from Staff "
            + " where " + srch_by + " LIKE '%"  + value + "%' order by " + srch_by + " desc ";
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            staff_jTable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_descMouseClicked

    private void con_yr_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con_yr_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_con_yr_tfActionPerformed

    private void up_salaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_up_salaryMouseClicked
        // TODO add your handling code here:
        Date da = (Date) leave_date_d.getDate();
        SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
        String l_date = dt.format(da);
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            int row = staff_jTable.getSelectedRow();
            String value = s_pay_id_tf.getText().toString();
            String query = "Update [Staff Salary] SET s_salary = ? ,leaving_date = ? ,s_bonus = ? where s_PAY_ID =" + value;
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, s_salary_tf.getText());
            pst.setString(2, l_date);
            pst.setString(3, s_bonus_tf.getText());

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Updated Sucessfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_up_salaryMouseClicked

    private void up_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_salaryActionPerformed

    private void up_msMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_up_msMouseClicked
        // TODO add your handling code here:
        Date da = (Date) injured_date_d.getDate();
        SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
        String i_date = dt.format(da);
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            int row = staff_jTable.getSelectedRow();
            String value = s_med_id_tf.getText().toString();
            String query = "Update [Staff Medical Status] SET LEAVE = ? ,M_Description = ?, Injured_date = ? where S_MED_ID = " + value;
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, s_leave_tf.getText());
            pst.setString(2, s_med_des_tf.getText());
            pst.setString(3, i_date);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Updated Sucessfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_up_msMouseClicked

    private void up_msActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_msActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_msActionPerformed
    
    public void image_choose() {
        JFileChooser choose = new JFileChooser();
        choose.showOpenDialog(null);
        File f = choose.getSelectedFile();
        fileName = f.getAbsolutePath();
        ImageIcon img_ic = new ImageIcon(new ImageIcon(fileName).getImage().getScaledInstance(img_l.getWidth(), img_l.getHeight(), Image.SCALE_SMOOTH));
        img_l.setIcon(img_ic);
        try {
            File image = new File(fileName);
            FileInputStream fi = new FileInputStream(image);
            ByteArrayOutputStream aos = new ByteArrayOutputStream();
            byte[] te = new byte[1024];
            for (int rn; (rn = fi.read(te)) != -1;) {
                aos.write(te, 0, rn);
            }
            staff_img = aos.toByteArray();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void ch_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch_btnActionPerformed
        // TODO add your handling code here:
        image_choose();
    }//GEN-LAST:event_ch_btnActionPerformed

    private void srch_p_range_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srch_p_range_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srch_p_range_2ActionPerformed

    private void srch_p_range_2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srch_p_range_2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_srch_p_range_2KeyReleased

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);

            TableModel model = staff_jTable.getModel();

            String value1 = srch_p_range_1.getText().trim();
            String value2 = srch_p_range_2.getText().trim();
            String srch_by = srch_by_com.toString();
            String query = "Select s_ID,s_NAME,s_type,s_AGE,s_SEX,s_M_issue from staff "
            + " where " + srch_by + " BETWEEN "  + value1 + " AND " + value2 + " order by " + srch_by;
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            staff_jTable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_okActionPerformed

    private void srch_p_range_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srch_p_range_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srch_p_range_1ActionPerformed

    private void srch_p_range_1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srch_p_range_1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_srch_p_range_1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Injured_date_l;
    private javax.swing.JLabel asc1;
    private javax.swing.JButton back_btn1;
    private javax.swing.JLabel c_y;
    private javax.swing.JButton ch_btn;
    private javax.swing.JButton clear_btn;
    private javax.swing.JTextField con_yr_tf;
    private javax.swing.JButton delete_btn;
    private javax.swing.JLabel desc;
    private javax.swing.JLabel description;
    private javax.swing.JRadioButton female_radio;
    private javax.swing.JLabel img_l;
    private com.toedter.calendar.JDateChooser injured_date_d;
    private javax.swing.JButton insert_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel leave;
    private com.toedter.calendar.JDateChooser leave_date_d;
    private javax.swing.JLabel leave_date_l;
    private javax.swing.JLabel m_id;
    private javax.swing.JRadioButton male_radio;
    private javax.swing.JButton ok;
    private javax.swing.JLabel p_id;
    private javax.swing.JButton refresh_btn;
    private javax.swing.JTextField s_age_tf;
    private javax.swing.JLabel s_b;
    private javax.swing.JTextField s_bonus_tf;
    private javax.swing.JTextField s_leave_tf;
    private javax.swing.JTextField s_med_des_tf;
    private javax.swing.JLabel s_med_id_tf;
    private javax.swing.JTextField s_name_tf;
    private javax.swing.JLabel s_pay_id_tf;
    private javax.swing.JLabel s_salary;
    private javax.swing.JTextField s_salary_tf;
    private javax.swing.JTextField s_type_tf;
    private javax.swing.JTextField search_s_name;
    private javax.swing.JTextField smissue_tf;
    private javax.swing.JComboBox<String> srch_by_combo;
    private javax.swing.JTextField srch_p_range_1;
    private javax.swing.JTextField srch_p_range_2;
    private javax.swing.JTable staff_jTable;
    private javax.swing.JTextField up_ms;
    private javax.swing.JTextField up_salary;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
