/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sponsors;

import Home.window;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Mahin Opu
 */
public class media extends javax.swing.JFrame {

    /**
     * Creates new form media
     */
    public media() {
        initComponents();
        show_media();
        
        Toolkit tk = getToolkit();
        Dimension size = tk.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }
    
    
public ArrayList<Sponsors.media_user> userList() {
        ArrayList<Sponsors.media_user> userslist = new ArrayList();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            String query1 = "SELECT * FROM Media";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);

            while (rs.next()) {
                Sponsors.media_user user=new Sponsors.media_user(rs.getInt("Media_Id"),rs.getString("Media_Type"),rs.getInt("Con_Year"),rs.getString("Revenue"),rs.getString("Media_Title"));
        //(rs.getInt("Media_Id"), rs.getString("Media_Type"), rs.getInt("Con_year"), rs.getDouble("Revenue"));
                userslist.add(user);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return userslist;
    }

 public void show_media() {
        ArrayList<Sponsors.media_user> list = userList();
        DefaultTableModel model = (DefaultTableModel) media_jtable.getModel();
        Object[] row = new Object[5];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getmId();
            row[1] = list.get(i).getmType();
            row[2] = list.get(i).getcontractYear();
            row[3] = list.get(i).getrevenue();
            row[4]=list.get(i).getmTitle();
            
            model.addRow(row);
        }
    }
 
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        m_type_combo = new javax.swing.JComboBox<>();
        con_year_tf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        revenue_tf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        m_title_tf = new javax.swing.JTextField();
        insert_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        clear_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        refresh_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        media_jtable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 505));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        m_type_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Broadcast", "Sponsor" }));
        m_type_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_type_comboActionPerformed(evt);
            }
        });
        getContentPane().add(m_type_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 110, 20));
        getContentPane().add(con_year_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 121, 20));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Revenue");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 50, 20));
        getContentPane().add(revenue_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 121, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Media Title");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, 20));
        getContentPane().add(m_title_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 121, -1));

        insert_btn.setText("Insert");
        insert_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_btnActionPerformed(evt);
            }
        });
        getContentPane().add(insert_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 68, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contract Year");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 20));

        clear_btn.setText("Clear");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });
        getContentPane().add(clear_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        getContentPane().add(update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        getContentPane().add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Media Type");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, 20));

        refresh_btn.setText("Refresh");
        refresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_btnActionPerformed(evt);
            }
        });
        getContentPane().add(refresh_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Media");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 70, 30));

        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        getContentPane().add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        media_jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Media_ID", "Media Type", "Contract Year", "Revenue", "Media Title"
            }
        ));
        media_jtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                media_jtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(media_jtable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 690, 180));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Staffs/gg.png"))); // NOI18N
        jLabel6.setIconTextGap(0);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 505));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insert_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_btnActionPerformed
        // TODO add your handling code here:
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            String query = "insert into [Media](Media_Type,Con_Year,Revenue,Media_Title)values(?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            String mtype_result=m_type_combo.getSelectedItem().toString();
            pst.setString(1,mtype_result);
            //pst.setString(1, m_type_tf.getText());
            pst.setString(2, con_year_tf.getText());
            pst.setString(3, revenue_tf.getText());
            pst.setString(4, m_title_tf.getText());
           
            
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) media_jtable.getModel();
            model.setRowCount(0);
            show_media();
           
             //pst.executeUpdate();
          

            JOptionPane.showMessageDialog(null, "Inserted Sucessfully!");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_insert_btnActionPerformed

    private void media_jtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_media_jtableMouseClicked
        // TODO add your handling code here:
         int i = media_jtable.getSelectedRow();
         TableModel model = media_jtable.getModel();
        

        //m_type_tf.setText(model.getValueAt(i, 1).toString());
           String mediatype1 = model.getValueAt(i, 1).toString();
           switch (mediatype1) {
            case "Brodcast":
                m_type_combo.setSelectedIndex(0);
                break;
            case "Sponsor":
                m_type_combo.setSelectedIndex(1);
                break;
        }

         con_year_tf.setText(model.getValueAt(i, 2).toString());

        revenue_tf.setText(model.getValueAt(i, 3).toString());
        
        m_title_tf.setText(model.getValueAt(i, 4).toString());
        

       
        /*
        try {
            byte[] img = (userList().get(i).getsImg());
            ImageIcon img_ic = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(image_label.getWidth(), image_label.getHeight(), Image.SCALE_SMOOTH));
            image_label.setIcon(img_ic);
           
        } catch (Exception e) {
            //clr_data();
            System.out.println(e);
        }
        */
    }//GEN-LAST:event_media_jtableMouseClicked

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:
       m_type_combo.setSelectedIndex(-1);
       con_year_tf.setText("");
       revenue_tf.setText("");
       m_title_tf.setText("");
    }//GEN-LAST:event_clear_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            int row = media_jtable.getSelectedRow();
            String value = (media_jtable.getModel().getValueAt(row, 0).toString());
            String query = "Update Media SET Media_Type = ? ,Con_Year = ? ,Revenue = ?,Media_Title=?  where Media_Id =" + value;
            PreparedStatement pst = con.prepareStatement(query);
            //pst.setString(1, m_type_tf.getText());
//            String m_result;
//            m_result = pos_combo1.getSelectedItem().toString();
//            pst.setString(2, m_result);
              String mtype_result=m_type_combo.getSelectedItem().toString();
              pst.setString(1,mtype_result);
//        
            pst.setString(2,con_year_tf.getText());
            pst.setString(3, revenue_tf.getText());
            pst.setString(4,m_title_tf.getText());
            

            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) media_jtable.getModel();
            model.setRowCount(0);
            show_media();
            

            JOptionPane.showMessageDialog(null, "Updated Sucessfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }        
    }//GEN-LAST:event_update_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
         int confirm = JOptionPane.showConfirmDialog(null, "Are you sure to Delete?", "Delete", JOptionPane.YES_NO_CANCEL_OPTION);
        if (confirm == 0) {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = "jdbc:sqlserver://localhost:1433;databaseName=Soccer_Club_Management_System;user=sa;password=123456";
                Connection con = DriverManager.getConnection(url);
                int row = media_jtable.getSelectedRow();
                String value = (media_jtable.getModel().getValueAt(row, 0).toString());
                
                
                
                String query = "Delete from Media where Media_Id =" + value;
                PreparedStatement pst = con.prepareStatement(query);
                pst.executeUpdate();
                
                DefaultTableModel model = (DefaultTableModel) media_jtable.getModel();
                model.setRowCount(0);
                show_media();
                
                 

                JOptionPane.showMessageDialog(null, "Deleted Sucessfully!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void refresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_btnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) media_jtable.getModel();
        model.setRowCount(0);
        show_media();
    }//GEN-LAST:event_refresh_btnActionPerformed

    private void m_type_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_type_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_type_comboActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        window field = new window();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(media.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(media.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(media.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(media.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new media().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JButton clear_btn;
    private javax.swing.JTextField con_year_tf;
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton insert_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField m_title_tf;
    private javax.swing.JComboBox<String> m_type_combo;
    private javax.swing.JTable media_jtable;
    private javax.swing.JButton refresh_btn;
    private javax.swing.JTextField revenue_tf;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
